// Code generated by ent, DO NOT EDIT.

package privatecustomersubscription

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the privatecustomersubscription type in the database.
	Label = "private_customer_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSubscriptionType holds the string denoting the subscription_type field in the database.
	FieldSubscriptionType = "subscription_type"
	// FieldAmountCents holds the string denoting the amount_cents field in the database.
	FieldAmountCents = "amount_cents"
	// FieldExpiresOn holds the string denoting the expires_on field in the database.
	FieldExpiresOn = "expires_on"
	// FieldReminderSentForExpiry holds the string denoting the reminder_sent_for_expiry field in the database.
	FieldReminderSentForExpiry = "reminder_sent_for_expiry"
	// FieldReminderSentAt holds the string denoting the reminder_sent_at field in the database.
	FieldReminderSentAt = "reminder_sent_at"
	// Table holds the table name of the privatecustomersubscription in the database.
	Table = "private_customer_subscriptions"
)

// Columns holds all SQL columns for privatecustomersubscription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldSubscriptionType,
	FieldAmountCents,
	FieldExpiresOn,
	FieldReminderSentForExpiry,
	FieldReminderSentAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SubscriptionTypeValidator is a validator for the "subscription_type" field. It is called by the builders before save.
	SubscriptionTypeValidator func(string) error
	// AmountCentsValidator is a validator for the "amount_cents" field. It is called by the builders before save.
	AmountCentsValidator func(int64) error
)

// OrderOption defines the ordering options for the PrivateCustomerSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySubscriptionType orders the results by the subscription_type field.
func BySubscriptionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionType, opts...).ToFunc()
}

// ByAmountCents orders the results by the amount_cents field.
func ByAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCents, opts...).ToFunc()
}

// ByExpiresOn orders the results by the expires_on field.
func ByExpiresOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresOn, opts...).ToFunc()
}

// ByReminderSentForExpiry orders the results by the reminder_sent_for_expiry field.
func ByReminderSentForExpiry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReminderSentForExpiry, opts...).ToFunc()
}

// ByReminderSentAt orders the results by the reminder_sent_at field.
func ByReminderSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReminderSentAt, opts...).ToFunc()
}
