// Code generated by ent, DO NOT EDIT.

package privatecustomersubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldName, v))
}

// SubscriptionType applies equality check predicate on the "subscription_type" field. It's identical to SubscriptionTypeEQ.
func SubscriptionType(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldSubscriptionType, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldAmountCents, v))
}

// ExpiresOn applies equality check predicate on the "expires_on" field. It's identical to ExpiresOnEQ.
func ExpiresOn(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldExpiresOn, v))
}

// ReminderSentForExpiry applies equality check predicate on the "reminder_sent_for_expiry" field. It's identical to ReminderSentForExpiryEQ.
func ReminderSentForExpiry(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldReminderSentForExpiry, v))
}

// ReminderSentAt applies equality check predicate on the "reminder_sent_at" field. It's identical to ReminderSentAtEQ.
func ReminderSentAt(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldReminderSentAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldContainsFold(FieldName, v))
}

// SubscriptionTypeEQ applies the EQ predicate on the "subscription_type" field.
func SubscriptionTypeEQ(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldSubscriptionType, v))
}

// SubscriptionTypeNEQ applies the NEQ predicate on the "subscription_type" field.
func SubscriptionTypeNEQ(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldSubscriptionType, v))
}

// SubscriptionTypeIn applies the In predicate on the "subscription_type" field.
func SubscriptionTypeIn(vs ...string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldSubscriptionType, vs...))
}

// SubscriptionTypeNotIn applies the NotIn predicate on the "subscription_type" field.
func SubscriptionTypeNotIn(vs ...string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldSubscriptionType, vs...))
}

// SubscriptionTypeGT applies the GT predicate on the "subscription_type" field.
func SubscriptionTypeGT(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldSubscriptionType, v))
}

// SubscriptionTypeGTE applies the GTE predicate on the "subscription_type" field.
func SubscriptionTypeGTE(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldSubscriptionType, v))
}

// SubscriptionTypeLT applies the LT predicate on the "subscription_type" field.
func SubscriptionTypeLT(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldSubscriptionType, v))
}

// SubscriptionTypeLTE applies the LTE predicate on the "subscription_type" field.
func SubscriptionTypeLTE(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldSubscriptionType, v))
}

// SubscriptionTypeContains applies the Contains predicate on the "subscription_type" field.
func SubscriptionTypeContains(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldContains(FieldSubscriptionType, v))
}

// SubscriptionTypeHasPrefix applies the HasPrefix predicate on the "subscription_type" field.
func SubscriptionTypeHasPrefix(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldHasPrefix(FieldSubscriptionType, v))
}

// SubscriptionTypeHasSuffix applies the HasSuffix predicate on the "subscription_type" field.
func SubscriptionTypeHasSuffix(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldHasSuffix(FieldSubscriptionType, v))
}

// SubscriptionTypeEqualFold applies the EqualFold predicate on the "subscription_type" field.
func SubscriptionTypeEqualFold(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEqualFold(FieldSubscriptionType, v))
}

// SubscriptionTypeContainsFold applies the ContainsFold predicate on the "subscription_type" field.
func SubscriptionTypeContainsFold(v string) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldContainsFold(FieldSubscriptionType, v))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldAmountCents, v))
}

// ExpiresOnEQ applies the EQ predicate on the "expires_on" field.
func ExpiresOnEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldExpiresOn, v))
}

// ExpiresOnNEQ applies the NEQ predicate on the "expires_on" field.
func ExpiresOnNEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldExpiresOn, v))
}

// ExpiresOnIn applies the In predicate on the "expires_on" field.
func ExpiresOnIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldExpiresOn, vs...))
}

// ExpiresOnNotIn applies the NotIn predicate on the "expires_on" field.
func ExpiresOnNotIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldExpiresOn, vs...))
}

// ExpiresOnGT applies the GT predicate on the "expires_on" field.
func ExpiresOnGT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldExpiresOn, v))
}

// ExpiresOnGTE applies the GTE predicate on the "expires_on" field.
func ExpiresOnGTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldExpiresOn, v))
}

// ExpiresOnLT applies the LT predicate on the "expires_on" field.
func ExpiresOnLT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldExpiresOn, v))
}

// ExpiresOnLTE applies the LTE predicate on the "expires_on" field.
func ExpiresOnLTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldExpiresOn, v))
}

// ReminderSentForExpiryEQ applies the EQ predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldReminderSentForExpiry, v))
}

// ReminderSentForExpiryNEQ applies the NEQ predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryNEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldReminderSentForExpiry, v))
}

// ReminderSentForExpiryIn applies the In predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldReminderSentForExpiry, vs...))
}

// ReminderSentForExpiryNotIn applies the NotIn predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryNotIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldReminderSentForExpiry, vs...))
}

// ReminderSentForExpiryGT applies the GT predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryGT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldReminderSentForExpiry, v))
}

// ReminderSentForExpiryGTE applies the GTE predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryGTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldReminderSentForExpiry, v))
}

// ReminderSentForExpiryLT applies the LT predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryLT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldReminderSentForExpiry, v))
}

// ReminderSentForExpiryLTE applies the LTE predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryLTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldReminderSentForExpiry, v))
}

// ReminderSentForExpiryIsNil applies the IsNil predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryIsNil() predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIsNull(FieldReminderSentForExpiry))
}

// ReminderSentForExpiryNotNil applies the NotNil predicate on the "reminder_sent_for_expiry" field.
func ReminderSentForExpiryNotNil() predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotNull(FieldReminderSentForExpiry))
}

// ReminderSentAtEQ applies the EQ predicate on the "reminder_sent_at" field.
func ReminderSentAtEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldEQ(FieldReminderSentAt, v))
}

// ReminderSentAtNEQ applies the NEQ predicate on the "reminder_sent_at" field.
func ReminderSentAtNEQ(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNEQ(FieldReminderSentAt, v))
}

// ReminderSentAtIn applies the In predicate on the "reminder_sent_at" field.
func ReminderSentAtIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIn(FieldReminderSentAt, vs...))
}

// ReminderSentAtNotIn applies the NotIn predicate on the "reminder_sent_at" field.
func ReminderSentAtNotIn(vs ...time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotIn(FieldReminderSentAt, vs...))
}

// ReminderSentAtGT applies the GT predicate on the "reminder_sent_at" field.
func ReminderSentAtGT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGT(FieldReminderSentAt, v))
}

// ReminderSentAtGTE applies the GTE predicate on the "reminder_sent_at" field.
func ReminderSentAtGTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldGTE(FieldReminderSentAt, v))
}

// ReminderSentAtLT applies the LT predicate on the "reminder_sent_at" field.
func ReminderSentAtLT(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLT(FieldReminderSentAt, v))
}

// ReminderSentAtLTE applies the LTE predicate on the "reminder_sent_at" field.
func ReminderSentAtLTE(v time.Time) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldLTE(FieldReminderSentAt, v))
}

// ReminderSentAtIsNil applies the IsNil predicate on the "reminder_sent_at" field.
func ReminderSentAtIsNil() predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldIsNull(FieldReminderSentAt))
}

// ReminderSentAtNotNil applies the NotNil predicate on the "reminder_sent_at" field.
func ReminderSentAtNotNil() predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.FieldNotNull(FieldReminderSentAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrivateCustomerSubscription) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrivateCustomerSubscription) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrivateCustomerSubscription) predicate.PrivateCustomerSubscription {
	return predicate.PrivateCustomerSubscription(sql.NotPredicates(p))
}
