// Code generated by ent, DO NOT EDIT.

package businessmonthlysnapshotitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the businessmonthlysnapshotitem type in the database.
	Label = "business_monthly_snapshot_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSnapshotID holds the string denoting the snapshot_id field in the database.
	FieldSnapshotID = "snapshot_id"
	// FieldItemType holds the string denoting the item_type field in the database.
	FieldItemType = "item_type"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldTier holds the string denoting the tier field in the database.
	FieldTier = "tier"
	// FieldOriginalAmountMinor holds the string denoting the original_amount_minor field in the database.
	FieldOriginalAmountMinor = "original_amount_minor"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRateScaled holds the string denoting the rate_scaled field in the database.
	FieldRateScaled = "rate_scaled"
	// FieldAmountCnyCents holds the string denoting the amount_cny_cents field in the database.
	FieldAmountCnyCents = "amount_cny_cents"
	// FieldExpiresOn holds the string denoting the expires_on field in the database.
	FieldExpiresOn = "expires_on"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldIncluded holds the string denoting the included field in the database.
	FieldIncluded = "included"
	// FieldLinkedAPIKeyID holds the string denoting the linked_api_key_id field in the database.
	FieldLinkedAPIKeyID = "linked_api_key_id"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// Table holds the table name of the businessmonthlysnapshotitem in the database.
	Table = "business_monthly_snapshot_items"
)

// Columns holds all SQL columns for businessmonthlysnapshotitem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSnapshotID,
	FieldItemType,
	FieldSourceType,
	FieldSourceID,
	FieldName,
	FieldCategory,
	FieldTier,
	FieldOriginalAmountMinor,
	FieldCurrency,
	FieldRateScaled,
	FieldAmountCnyCents,
	FieldExpiresOn,
	FieldReason,
	FieldIncluded,
	FieldLinkedAPIKeyID,
	FieldGroupName,
	FieldUserEmail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ItemTypeValidator is a validator for the "item_type" field. It is called by the builders before save.
	ItemTypeValidator func(string) error
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// TierValidator is a validator for the "tier" field. It is called by the builders before save.
	TierValidator func(string) error
	// DefaultOriginalAmountMinor holds the default value on creation for the "original_amount_minor" field.
	DefaultOriginalAmountMinor int64
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultRateScaled holds the default value on creation for the "rate_scaled" field.
	DefaultRateScaled int64
	// RateScaledValidator is a validator for the "rate_scaled" field. It is called by the builders before save.
	RateScaledValidator func(int64) error
	// DefaultAmountCnyCents holds the default value on creation for the "amount_cny_cents" field.
	DefaultAmountCnyCents int64
	// DefaultIncluded holds the default value on creation for the "included" field.
	DefaultIncluded bool
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
)

// OrderOption defines the ordering options for the BusinessMonthlySnapshotItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySnapshotID orders the results by the snapshot_id field.
func BySnapshotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotID, opts...).ToFunc()
}

// ByItemType orders the results by the item_type field.
func ByItemType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemType, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByTier orders the results by the tier field.
func ByTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTier, opts...).ToFunc()
}

// ByOriginalAmountMinor orders the results by the original_amount_minor field.
func ByOriginalAmountMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalAmountMinor, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRateScaled orders the results by the rate_scaled field.
func ByRateScaled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateScaled, opts...).ToFunc()
}

// ByAmountCnyCents orders the results by the amount_cny_cents field.
func ByAmountCnyCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCnyCents, opts...).ToFunc()
}

// ByExpiresOn orders the results by the expires_on field.
func ByExpiresOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresOn, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByIncluded orders the results by the included field.
func ByIncluded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncluded, opts...).ToFunc()
}

// ByLinkedAPIKeyID orders the results by the linked_api_key_id field.
func ByLinkedAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedAPIKeyID, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}
