// Code generated by ent, DO NOT EDIT.

package businessmonthlysnapshotitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// SnapshotID applies equality check predicate on the "snapshot_id" field. It's identical to SnapshotIDEQ.
func SnapshotID(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldSnapshotID, v))
}

// ItemType applies equality check predicate on the "item_type" field. It's identical to ItemTypeEQ.
func ItemType(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldItemType, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldSourceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldName, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldCategory, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldTier, v))
}

// OriginalAmountMinor applies equality check predicate on the "original_amount_minor" field. It's identical to OriginalAmountMinorEQ.
func OriginalAmountMinor(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldOriginalAmountMinor, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldCurrency, v))
}

// RateScaled applies equality check predicate on the "rate_scaled" field. It's identical to RateScaledEQ.
func RateScaled(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldRateScaled, v))
}

// AmountCnyCents applies equality check predicate on the "amount_cny_cents" field. It's identical to AmountCnyCentsEQ.
func AmountCnyCents(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldAmountCnyCents, v))
}

// ExpiresOn applies equality check predicate on the "expires_on" field. It's identical to ExpiresOnEQ.
func ExpiresOn(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldExpiresOn, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldReason, v))
}

// Included applies equality check predicate on the "included" field. It's identical to IncludedEQ.
func Included(v bool) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldIncluded, v))
}

// LinkedAPIKeyID applies equality check predicate on the "linked_api_key_id" field. It's identical to LinkedAPIKeyIDEQ.
func LinkedAPIKeyID(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldLinkedAPIKeyID, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldGroupName, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldUserEmail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// SnapshotIDEQ applies the EQ predicate on the "snapshot_id" field.
func SnapshotIDEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldSnapshotID, v))
}

// SnapshotIDNEQ applies the NEQ predicate on the "snapshot_id" field.
func SnapshotIDNEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldSnapshotID, v))
}

// SnapshotIDIn applies the In predicate on the "snapshot_id" field.
func SnapshotIDIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldSnapshotID, vs...))
}

// SnapshotIDNotIn applies the NotIn predicate on the "snapshot_id" field.
func SnapshotIDNotIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldSnapshotID, vs...))
}

// SnapshotIDGT applies the GT predicate on the "snapshot_id" field.
func SnapshotIDGT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldSnapshotID, v))
}

// SnapshotIDGTE applies the GTE predicate on the "snapshot_id" field.
func SnapshotIDGTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldSnapshotID, v))
}

// SnapshotIDLT applies the LT predicate on the "snapshot_id" field.
func SnapshotIDLT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldSnapshotID, v))
}

// SnapshotIDLTE applies the LTE predicate on the "snapshot_id" field.
func SnapshotIDLTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldSnapshotID, v))
}

// ItemTypeEQ applies the EQ predicate on the "item_type" field.
func ItemTypeEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldItemType, v))
}

// ItemTypeNEQ applies the NEQ predicate on the "item_type" field.
func ItemTypeNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldItemType, v))
}

// ItemTypeIn applies the In predicate on the "item_type" field.
func ItemTypeIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldItemType, vs...))
}

// ItemTypeNotIn applies the NotIn predicate on the "item_type" field.
func ItemTypeNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldItemType, vs...))
}

// ItemTypeGT applies the GT predicate on the "item_type" field.
func ItemTypeGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldItemType, v))
}

// ItemTypeGTE applies the GTE predicate on the "item_type" field.
func ItemTypeGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldItemType, v))
}

// ItemTypeLT applies the LT predicate on the "item_type" field.
func ItemTypeLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldItemType, v))
}

// ItemTypeLTE applies the LTE predicate on the "item_type" field.
func ItemTypeLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldItemType, v))
}

// ItemTypeContains applies the Contains predicate on the "item_type" field.
func ItemTypeContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldItemType, v))
}

// ItemTypeHasPrefix applies the HasPrefix predicate on the "item_type" field.
func ItemTypeHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldItemType, v))
}

// ItemTypeHasSuffix applies the HasSuffix predicate on the "item_type" field.
func ItemTypeHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldItemType, v))
}

// ItemTypeEqualFold applies the EqualFold predicate on the "item_type" field.
func ItemTypeEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldItemType, v))
}

// ItemTypeContainsFold applies the ContainsFold predicate on the "item_type" field.
func ItemTypeContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldItemType, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldSourceID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldName, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldCategory, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldTier, v))
}

// TierContains applies the Contains predicate on the "tier" field.
func TierContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldTier, v))
}

// TierHasPrefix applies the HasPrefix predicate on the "tier" field.
func TierHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldTier, v))
}

// TierHasSuffix applies the HasSuffix predicate on the "tier" field.
func TierHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldTier, v))
}

// TierIsNil applies the IsNil predicate on the "tier" field.
func TierIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldTier))
}

// TierNotNil applies the NotNil predicate on the "tier" field.
func TierNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldTier))
}

// TierEqualFold applies the EqualFold predicate on the "tier" field.
func TierEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldTier, v))
}

// TierContainsFold applies the ContainsFold predicate on the "tier" field.
func TierContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldTier, v))
}

// OriginalAmountMinorEQ applies the EQ predicate on the "original_amount_minor" field.
func OriginalAmountMinorEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldOriginalAmountMinor, v))
}

// OriginalAmountMinorNEQ applies the NEQ predicate on the "original_amount_minor" field.
func OriginalAmountMinorNEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldOriginalAmountMinor, v))
}

// OriginalAmountMinorIn applies the In predicate on the "original_amount_minor" field.
func OriginalAmountMinorIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldOriginalAmountMinor, vs...))
}

// OriginalAmountMinorNotIn applies the NotIn predicate on the "original_amount_minor" field.
func OriginalAmountMinorNotIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldOriginalAmountMinor, vs...))
}

// OriginalAmountMinorGT applies the GT predicate on the "original_amount_minor" field.
func OriginalAmountMinorGT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldOriginalAmountMinor, v))
}

// OriginalAmountMinorGTE applies the GTE predicate on the "original_amount_minor" field.
func OriginalAmountMinorGTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldOriginalAmountMinor, v))
}

// OriginalAmountMinorLT applies the LT predicate on the "original_amount_minor" field.
func OriginalAmountMinorLT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldOriginalAmountMinor, v))
}

// OriginalAmountMinorLTE applies the LTE predicate on the "original_amount_minor" field.
func OriginalAmountMinorLTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldOriginalAmountMinor, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldCurrency, v))
}

// RateScaledEQ applies the EQ predicate on the "rate_scaled" field.
func RateScaledEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldRateScaled, v))
}

// RateScaledNEQ applies the NEQ predicate on the "rate_scaled" field.
func RateScaledNEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldRateScaled, v))
}

// RateScaledIn applies the In predicate on the "rate_scaled" field.
func RateScaledIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldRateScaled, vs...))
}

// RateScaledNotIn applies the NotIn predicate on the "rate_scaled" field.
func RateScaledNotIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldRateScaled, vs...))
}

// RateScaledGT applies the GT predicate on the "rate_scaled" field.
func RateScaledGT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldRateScaled, v))
}

// RateScaledGTE applies the GTE predicate on the "rate_scaled" field.
func RateScaledGTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldRateScaled, v))
}

// RateScaledLT applies the LT predicate on the "rate_scaled" field.
func RateScaledLT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldRateScaled, v))
}

// RateScaledLTE applies the LTE predicate on the "rate_scaled" field.
func RateScaledLTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldRateScaled, v))
}

// AmountCnyCentsEQ applies the EQ predicate on the "amount_cny_cents" field.
func AmountCnyCentsEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldAmountCnyCents, v))
}

// AmountCnyCentsNEQ applies the NEQ predicate on the "amount_cny_cents" field.
func AmountCnyCentsNEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldAmountCnyCents, v))
}

// AmountCnyCentsIn applies the In predicate on the "amount_cny_cents" field.
func AmountCnyCentsIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldAmountCnyCents, vs...))
}

// AmountCnyCentsNotIn applies the NotIn predicate on the "amount_cny_cents" field.
func AmountCnyCentsNotIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldAmountCnyCents, vs...))
}

// AmountCnyCentsGT applies the GT predicate on the "amount_cny_cents" field.
func AmountCnyCentsGT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldAmountCnyCents, v))
}

// AmountCnyCentsGTE applies the GTE predicate on the "amount_cny_cents" field.
func AmountCnyCentsGTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldAmountCnyCents, v))
}

// AmountCnyCentsLT applies the LT predicate on the "amount_cny_cents" field.
func AmountCnyCentsLT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldAmountCnyCents, v))
}

// AmountCnyCentsLTE applies the LTE predicate on the "amount_cny_cents" field.
func AmountCnyCentsLTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldAmountCnyCents, v))
}

// ExpiresOnEQ applies the EQ predicate on the "expires_on" field.
func ExpiresOnEQ(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldExpiresOn, v))
}

// ExpiresOnNEQ applies the NEQ predicate on the "expires_on" field.
func ExpiresOnNEQ(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldExpiresOn, v))
}

// ExpiresOnIn applies the In predicate on the "expires_on" field.
func ExpiresOnIn(vs ...time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldExpiresOn, vs...))
}

// ExpiresOnNotIn applies the NotIn predicate on the "expires_on" field.
func ExpiresOnNotIn(vs ...time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldExpiresOn, vs...))
}

// ExpiresOnGT applies the GT predicate on the "expires_on" field.
func ExpiresOnGT(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldExpiresOn, v))
}

// ExpiresOnGTE applies the GTE predicate on the "expires_on" field.
func ExpiresOnGTE(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldExpiresOn, v))
}

// ExpiresOnLT applies the LT predicate on the "expires_on" field.
func ExpiresOnLT(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldExpiresOn, v))
}

// ExpiresOnLTE applies the LTE predicate on the "expires_on" field.
func ExpiresOnLTE(v time.Time) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldExpiresOn, v))
}

// ExpiresOnIsNil applies the IsNil predicate on the "expires_on" field.
func ExpiresOnIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldExpiresOn))
}

// ExpiresOnNotNil applies the NotNil predicate on the "expires_on" field.
func ExpiresOnNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldExpiresOn))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldReason, v))
}

// IncludedEQ applies the EQ predicate on the "included" field.
func IncludedEQ(v bool) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldIncluded, v))
}

// IncludedNEQ applies the NEQ predicate on the "included" field.
func IncludedNEQ(v bool) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldIncluded, v))
}

// LinkedAPIKeyIDEQ applies the EQ predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldLinkedAPIKeyID, v))
}

// LinkedAPIKeyIDNEQ applies the NEQ predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDNEQ(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldLinkedAPIKeyID, v))
}

// LinkedAPIKeyIDIn applies the In predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldLinkedAPIKeyID, vs...))
}

// LinkedAPIKeyIDNotIn applies the NotIn predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDNotIn(vs ...int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldLinkedAPIKeyID, vs...))
}

// LinkedAPIKeyIDGT applies the GT predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDGT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldLinkedAPIKeyID, v))
}

// LinkedAPIKeyIDGTE applies the GTE predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDGTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldLinkedAPIKeyID, v))
}

// LinkedAPIKeyIDLT applies the LT predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDLT(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldLinkedAPIKeyID, v))
}

// LinkedAPIKeyIDLTE applies the LTE predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDLTE(v int64) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldLinkedAPIKeyID, v))
}

// LinkedAPIKeyIDIsNil applies the IsNil predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldLinkedAPIKeyID))
}

// LinkedAPIKeyIDNotNil applies the NotNil predicate on the "linked_api_key_id" field.
func LinkedAPIKeyIDNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldLinkedAPIKeyID))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameIsNil applies the IsNil predicate on the "group_name" field.
func GroupNameIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldGroupName))
}

// GroupNameNotNil applies the NotNil predicate on the "group_name" field.
func GroupNameNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldGroupName))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldGroupName, v))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailIsNil applies the IsNil predicate on the "user_email" field.
func UserEmailIsNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldIsNull(FieldUserEmail))
}

// UserEmailNotNil applies the NotNil predicate on the "user_email" field.
func UserEmailNotNil() predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldNotNull(FieldUserEmail))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.FieldContainsFold(FieldUserEmail, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BusinessMonthlySnapshotItem) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BusinessMonthlySnapshotItem) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BusinessMonthlySnapshotItem) predicate.BusinessMonthlySnapshotItem {
	return predicate.BusinessMonthlySnapshotItem(sql.NotPredicates(p))
}
