// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/businessmonthlysnapshot"
)

// BusinessMonthlySnapshot is the model entity for the BusinessMonthlySnapshot schema.
type BusinessMonthlySnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Month holds the value of the "month" field.
	Month time.Time `json:"month,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// DataQuality holds the value of the "data_quality" field.
	DataQuality string `json:"data_quality,omitempty"`
	// APIKeyCount holds the value of the "api_key_count" field.
	APIKeyCount int `json:"api_key_count,omitempty"`
	// PrivateSubscriptionCount holds the value of the "private_subscription_count" field.
	PrivateSubscriptionCount int `json:"private_subscription_count,omitempty"`
	// CustomerCount holds the value of the "customer_count" field.
	CustomerCount int `json:"customer_count,omitempty"`
	// ExcludedAPIKeyCount holds the value of the "excluded_api_key_count" field.
	ExcludedAPIKeyCount int `json:"excluded_api_key_count,omitempty"`
	// AnomalyCount holds the value of the "anomaly_count" field.
	AnomalyCount int `json:"anomaly_count,omitempty"`
	// APIKeyRevenueCents holds the value of the "api_key_revenue_cents" field.
	APIKeyRevenueCents int64 `json:"api_key_revenue_cents,omitempty"`
	// PrivateSubscriptionRevenueCents holds the value of the "private_subscription_revenue_cents" field.
	PrivateSubscriptionRevenueCents int64 `json:"private_subscription_revenue_cents,omitempty"`
	// TotalRevenueCents holds the value of the "total_revenue_cents" field.
	TotalRevenueCents int64 `json:"total_revenue_cents,omitempty"`
	// DirectCostCents holds the value of the "direct_cost_cents" field.
	DirectCostCents int64 `json:"direct_cost_cents,omitempty"`
	// OperatingCostCents holds the value of the "operating_cost_cents" field.
	OperatingCostCents int64 `json:"operating_cost_cents,omitempty"`
	// GrossProfitCents holds the value of the "gross_profit_cents" field.
	GrossProfitCents int64 `json:"gross_profit_cents,omitempty"`
	// NetProfitCents holds the value of the "net_profit_cents" field.
	NetProfitCents int64 `json:"net_profit_cents,omitempty"`
	// GrossMarginBps holds the value of the "gross_margin_bps" field.
	GrossMarginBps int64 `json:"gross_margin_bps,omitempty"`
	// NetMarginBps holds the value of the "net_margin_bps" field.
	NetMarginBps int64 `json:"net_margin_bps,omitempty"`
	// CostsComplete holds the value of the "costs_complete" field.
	CostsComplete bool `json:"costs_complete,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt time.Time `json:"closed_at,omitempty"`
	// ClosedBy holds the value of the "closed_by" field.
	ClosedBy     *int64 `json:"closed_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BusinessMonthlySnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case businessmonthlysnapshot.FieldCostsComplete:
			values[i] = new(sql.NullBool)
		case businessmonthlysnapshot.FieldID, businessmonthlysnapshot.FieldAPIKeyCount, businessmonthlysnapshot.FieldPrivateSubscriptionCount, businessmonthlysnapshot.FieldCustomerCount, businessmonthlysnapshot.FieldExcludedAPIKeyCount, businessmonthlysnapshot.FieldAnomalyCount, businessmonthlysnapshot.FieldAPIKeyRevenueCents, businessmonthlysnapshot.FieldPrivateSubscriptionRevenueCents, businessmonthlysnapshot.FieldTotalRevenueCents, businessmonthlysnapshot.FieldDirectCostCents, businessmonthlysnapshot.FieldOperatingCostCents, businessmonthlysnapshot.FieldGrossProfitCents, businessmonthlysnapshot.FieldNetProfitCents, businessmonthlysnapshot.FieldGrossMarginBps, businessmonthlysnapshot.FieldNetMarginBps, businessmonthlysnapshot.FieldClosedBy:
			values[i] = new(sql.NullInt64)
		case businessmonthlysnapshot.FieldStatus, businessmonthlysnapshot.FieldDataQuality, businessmonthlysnapshot.FieldNotes:
			values[i] = new(sql.NullString)
		case businessmonthlysnapshot.FieldCreatedAt, businessmonthlysnapshot.FieldUpdatedAt, businessmonthlysnapshot.FieldMonth, businessmonthlysnapshot.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BusinessMonthlySnapshot fields.
func (_m *BusinessMonthlySnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case businessmonthlysnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case businessmonthlysnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case businessmonthlysnapshot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case businessmonthlysnapshot.FieldMonth:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field month", values[i])
			} else if value.Valid {
				_m.Month = value.Time
			}
		case businessmonthlysnapshot.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case businessmonthlysnapshot.FieldDataQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_quality", values[i])
			} else if value.Valid {
				_m.DataQuality = value.String
			}
		case businessmonthlysnapshot.FieldAPIKeyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_count", values[i])
			} else if value.Valid {
				_m.APIKeyCount = int(value.Int64)
			}
		case businessmonthlysnapshot.FieldPrivateSubscriptionCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field private_subscription_count", values[i])
			} else if value.Valid {
				_m.PrivateSubscriptionCount = int(value.Int64)
			}
		case businessmonthlysnapshot.FieldCustomerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field customer_count", values[i])
			} else if value.Valid {
				_m.CustomerCount = int(value.Int64)
			}
		case businessmonthlysnapshot.FieldExcludedAPIKeyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field excluded_api_key_count", values[i])
			} else if value.Valid {
				_m.ExcludedAPIKeyCount = int(value.Int64)
			}
		case businessmonthlysnapshot.FieldAnomalyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field anomaly_count", values[i])
			} else if value.Valid {
				_m.AnomalyCount = int(value.Int64)
			}
		case businessmonthlysnapshot.FieldAPIKeyRevenueCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_revenue_cents", values[i])
			} else if value.Valid {
				_m.APIKeyRevenueCents = value.Int64
			}
		case businessmonthlysnapshot.FieldPrivateSubscriptionRevenueCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field private_subscription_revenue_cents", values[i])
			} else if value.Valid {
				_m.PrivateSubscriptionRevenueCents = value.Int64
			}
		case businessmonthlysnapshot.FieldTotalRevenueCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_revenue_cents", values[i])
			} else if value.Valid {
				_m.TotalRevenueCents = value.Int64
			}
		case businessmonthlysnapshot.FieldDirectCostCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field direct_cost_cents", values[i])
			} else if value.Valid {
				_m.DirectCostCents = value.Int64
			}
		case businessmonthlysnapshot.FieldOperatingCostCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operating_cost_cents", values[i])
			} else if value.Valid {
				_m.OperatingCostCents = value.Int64
			}
		case businessmonthlysnapshot.FieldGrossProfitCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gross_profit_cents", values[i])
			} else if value.Valid {
				_m.GrossProfitCents = value.Int64
			}
		case businessmonthlysnapshot.FieldNetProfitCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field net_profit_cents", values[i])
			} else if value.Valid {
				_m.NetProfitCents = value.Int64
			}
		case businessmonthlysnapshot.FieldGrossMarginBps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gross_margin_bps", values[i])
			} else if value.Valid {
				_m.GrossMarginBps = value.Int64
			}
		case businessmonthlysnapshot.FieldNetMarginBps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field net_margin_bps", values[i])
			} else if value.Valid {
				_m.NetMarginBps = value.Int64
			}
		case businessmonthlysnapshot.FieldCostsComplete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field costs_complete", values[i])
			} else if value.Valid {
				_m.CostsComplete = value.Bool
			}
		case businessmonthlysnapshot.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case businessmonthlysnapshot.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = value.Time
			}
		case businessmonthlysnapshot.FieldClosedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field closed_by", values[i])
			} else if value.Valid {
				_m.ClosedBy = new(int64)
				*_m.ClosedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BusinessMonthlySnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *BusinessMonthlySnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BusinessMonthlySnapshot.
// Note that you need to call BusinessMonthlySnapshot.Unwrap() before calling this method if this BusinessMonthlySnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BusinessMonthlySnapshot) Update() *BusinessMonthlySnapshotUpdateOne {
	return NewBusinessMonthlySnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BusinessMonthlySnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BusinessMonthlySnapshot) Unwrap() *BusinessMonthlySnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BusinessMonthlySnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BusinessMonthlySnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("BusinessMonthlySnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("month=")
	builder.WriteString(_m.Month.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("data_quality=")
	builder.WriteString(_m.DataQuality)
	builder.WriteString(", ")
	builder.WriteString("api_key_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyCount))
	builder.WriteString(", ")
	builder.WriteString("private_subscription_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrivateSubscriptionCount))
	builder.WriteString(", ")
	builder.WriteString("customer_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomerCount))
	builder.WriteString(", ")
	builder.WriteString("excluded_api_key_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExcludedAPIKeyCount))
	builder.WriteString(", ")
	builder.WriteString("anomaly_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnomalyCount))
	builder.WriteString(", ")
	builder.WriteString("api_key_revenue_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyRevenueCents))
	builder.WriteString(", ")
	builder.WriteString("private_subscription_revenue_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrivateSubscriptionRevenueCents))
	builder.WriteString(", ")
	builder.WriteString("total_revenue_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRevenueCents))
	builder.WriteString(", ")
	builder.WriteString("direct_cost_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.DirectCostCents))
	builder.WriteString(", ")
	builder.WriteString("operating_cost_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatingCostCents))
	builder.WriteString(", ")
	builder.WriteString("gross_profit_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrossProfitCents))
	builder.WriteString(", ")
	builder.WriteString("net_profit_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetProfitCents))
	builder.WriteString(", ")
	builder.WriteString("gross_margin_bps=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrossMarginBps))
	builder.WriteString(", ")
	builder.WriteString("net_margin_bps=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetMarginBps))
	builder.WriteString(", ")
	builder.WriteString("costs_complete=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostsComplete))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("closed_at=")
	builder.WriteString(_m.ClosedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedBy; v != nil {
		builder.WriteString("closed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BusinessMonthlySnapshots is a parsable slice of BusinessMonthlySnapshot.
type BusinessMonthlySnapshots []*BusinessMonthlySnapshot
