// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/businessexchangerate"
)

// BusinessExchangeRate is the model entity for the BusinessExchangeRate schema.
type BusinessExchangeRate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Month holds the value of the "month" field.
	Month time.Time `json:"month,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RateScaled holds the value of the "rate_scaled" field.
	RateScaled int64 `json:"rate_scaled,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        *string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BusinessExchangeRate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case businessexchangerate.FieldID, businessexchangerate.FieldRateScaled:
			values[i] = new(sql.NullInt64)
		case businessexchangerate.FieldCurrency, businessexchangerate.FieldSource, businessexchangerate.FieldNotes:
			values[i] = new(sql.NullString)
		case businessexchangerate.FieldCreatedAt, businessexchangerate.FieldUpdatedAt, businessexchangerate.FieldMonth:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BusinessExchangeRate fields.
func (_m *BusinessExchangeRate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case businessexchangerate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case businessexchangerate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case businessexchangerate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case businessexchangerate.FieldMonth:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field month", values[i])
			} else if value.Valid {
				_m.Month = value.Time
			}
		case businessexchangerate.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case businessexchangerate.FieldRateScaled:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_scaled", values[i])
			} else if value.Valid {
				_m.RateScaled = value.Int64
			}
		case businessexchangerate.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case businessexchangerate.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BusinessExchangeRate.
// This includes values selected through modifiers, order, etc.
func (_m *BusinessExchangeRate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BusinessExchangeRate.
// Note that you need to call BusinessExchangeRate.Unwrap() before calling this method if this BusinessExchangeRate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BusinessExchangeRate) Update() *BusinessExchangeRateUpdateOne {
	return NewBusinessExchangeRateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BusinessExchangeRate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BusinessExchangeRate) Unwrap() *BusinessExchangeRate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BusinessExchangeRate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BusinessExchangeRate) String() string {
	var builder strings.Builder
	builder.WriteString("BusinessExchangeRate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("month=")
	builder.WriteString(_m.Month.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("rate_scaled=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateScaled))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BusinessExchangeRates is a parsable slice of BusinessExchangeRate.
type BusinessExchangeRates []*BusinessExchangeRate
