// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/businessapikeyconfig"
)

// BusinessAPIKeyConfig is the model entity for the BusinessAPIKeyConfig schema.
type BusinessAPIKeyConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// RevenueExcluded holds the value of the "revenue_excluded" field.
	RevenueExcluded bool `json:"revenue_excluded,omitempty"`
	// OverrideAmountCents holds the value of the "override_amount_cents" field.
	OverrideAmountCents *int64 `json:"override_amount_cents,omitempty"`
	// PrivateSubscriptionID holds the value of the "private_subscription_id" field.
	PrivateSubscriptionID *int64 `json:"private_subscription_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason       *string `json:"reason,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BusinessAPIKeyConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case businessapikeyconfig.FieldRevenueExcluded:
			values[i] = new(sql.NullBool)
		case businessapikeyconfig.FieldID, businessapikeyconfig.FieldAPIKeyID, businessapikeyconfig.FieldOverrideAmountCents, businessapikeyconfig.FieldPrivateSubscriptionID:
			values[i] = new(sql.NullInt64)
		case businessapikeyconfig.FieldReason:
			values[i] = new(sql.NullString)
		case businessapikeyconfig.FieldCreatedAt, businessapikeyconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BusinessAPIKeyConfig fields.
func (_m *BusinessAPIKeyConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case businessapikeyconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case businessapikeyconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case businessapikeyconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case businessapikeyconfig.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case businessapikeyconfig.FieldRevenueExcluded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revenue_excluded", values[i])
			} else if value.Valid {
				_m.RevenueExcluded = value.Bool
			}
		case businessapikeyconfig.FieldOverrideAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field override_amount_cents", values[i])
			} else if value.Valid {
				_m.OverrideAmountCents = new(int64)
				*_m.OverrideAmountCents = value.Int64
			}
		case businessapikeyconfig.FieldPrivateSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field private_subscription_id", values[i])
			} else if value.Valid {
				_m.PrivateSubscriptionID = new(int64)
				*_m.PrivateSubscriptionID = value.Int64
			}
		case businessapikeyconfig.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BusinessAPIKeyConfig.
// This includes values selected through modifiers, order, etc.
func (_m *BusinessAPIKeyConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BusinessAPIKeyConfig.
// Note that you need to call BusinessAPIKeyConfig.Unwrap() before calling this method if this BusinessAPIKeyConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BusinessAPIKeyConfig) Update() *BusinessAPIKeyConfigUpdateOne {
	return NewBusinessAPIKeyConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BusinessAPIKeyConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BusinessAPIKeyConfig) Unwrap() *BusinessAPIKeyConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BusinessAPIKeyConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BusinessAPIKeyConfig) String() string {
	var builder strings.Builder
	builder.WriteString("BusinessAPIKeyConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("revenue_excluded=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevenueExcluded))
	builder.WriteString(", ")
	if v := _m.OverrideAmountCents; v != nil {
		builder.WriteString("override_amount_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PrivateSubscriptionID; v != nil {
		builder.WriteString("private_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BusinessAPIKeyConfigs is a parsable slice of BusinessAPIKeyConfig.
type BusinessAPIKeyConfigs []*BusinessAPIKeyConfig
