// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessapikeyconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BusinessAPIKeyConfigDelete is the builder for deleting a BusinessAPIKeyConfig entity.
type BusinessAPIKeyConfigDelete struct {
	config
	hooks    []Hook
	mutation *BusinessAPIKeyConfigMutation
}

// Where appends a list predicates to the BusinessAPIKeyConfigDelete builder.
func (_d *BusinessAPIKeyConfigDelete) Where(ps ...predicate.BusinessAPIKeyConfig) *BusinessAPIKeyConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BusinessAPIKeyConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessAPIKeyConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BusinessAPIKeyConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(businessapikeyconfig.Table, sqlgraph.NewFieldSpec(businessapikeyconfig.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BusinessAPIKeyConfigDeleteOne is the builder for deleting a single BusinessAPIKeyConfig entity.
type BusinessAPIKeyConfigDeleteOne struct {
	_d *BusinessAPIKeyConfigDelete
}

// Where appends a list predicates to the BusinessAPIKeyConfigDelete builder.
func (_d *BusinessAPIKeyConfigDeleteOne) Where(ps ...predicate.BusinessAPIKeyConfig) *BusinessAPIKeyConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BusinessAPIKeyConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{businessapikeyconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessAPIKeyConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
