// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessexchangerate"
)

// BusinessExchangeRateCreate is the builder for creating a BusinessExchangeRate entity.
type BusinessExchangeRateCreate struct {
	config
	mutation *BusinessExchangeRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BusinessExchangeRateCreate) SetCreatedAt(v time.Time) *BusinessExchangeRateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BusinessExchangeRateCreate) SetNillableCreatedAt(v *time.Time) *BusinessExchangeRateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BusinessExchangeRateCreate) SetUpdatedAt(v time.Time) *BusinessExchangeRateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BusinessExchangeRateCreate) SetNillableUpdatedAt(v *time.Time) *BusinessExchangeRateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMonth sets the "month" field.
func (_c *BusinessExchangeRateCreate) SetMonth(v time.Time) *BusinessExchangeRateCreate {
	_c.mutation.SetMonth(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BusinessExchangeRateCreate) SetCurrency(v string) *BusinessExchangeRateCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetRateScaled sets the "rate_scaled" field.
func (_c *BusinessExchangeRateCreate) SetRateScaled(v int64) *BusinessExchangeRateCreate {
	_c.mutation.SetRateScaled(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *BusinessExchangeRateCreate) SetSource(v string) *BusinessExchangeRateCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *BusinessExchangeRateCreate) SetNillableSource(v *string) *BusinessExchangeRateCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *BusinessExchangeRateCreate) SetNotes(v string) *BusinessExchangeRateCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *BusinessExchangeRateCreate) SetNillableNotes(v *string) *BusinessExchangeRateCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// Mutation returns the BusinessExchangeRateMutation object of the builder.
func (_c *BusinessExchangeRateCreate) Mutation() *BusinessExchangeRateMutation {
	return _c.mutation
}

// Save creates the BusinessExchangeRate in the database.
func (_c *BusinessExchangeRateCreate) Save(ctx context.Context) (*BusinessExchangeRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BusinessExchangeRateCreate) SaveX(ctx context.Context) *BusinessExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BusinessExchangeRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BusinessExchangeRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BusinessExchangeRateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := businessexchangerate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := businessexchangerate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := businessexchangerate.DefaultSource
		_c.mutation.SetSource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BusinessExchangeRateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BusinessExchangeRate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BusinessExchangeRate.updated_at"`)}
	}
	if _, ok := _c.mutation.Month(); !ok {
		return &ValidationError{Name: "month", err: errors.New(`ent: missing required field "BusinessExchangeRate.month"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BusinessExchangeRate.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := businessexchangerate.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BusinessExchangeRate.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateScaled(); !ok {
		return &ValidationError{Name: "rate_scaled", err: errors.New(`ent: missing required field "BusinessExchangeRate.rate_scaled"`)}
	}
	if v, ok := _c.mutation.RateScaled(); ok {
		if err := businessexchangerate.RateScaledValidator(v); err != nil {
			return &ValidationError{Name: "rate_scaled", err: fmt.Errorf(`ent: validator failed for field "BusinessExchangeRate.rate_scaled": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "BusinessExchangeRate.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := businessexchangerate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "BusinessExchangeRate.source": %w`, err)}
		}
	}
	return nil
}

func (_c *BusinessExchangeRateCreate) sqlSave(ctx context.Context) (*BusinessExchangeRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BusinessExchangeRateCreate) createSpec() (*BusinessExchangeRate, *sqlgraph.CreateSpec) {
	var (
		_node = &BusinessExchangeRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(businessexchangerate.Table, sqlgraph.NewFieldSpec(businessexchangerate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(businessexchangerate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(businessexchangerate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Month(); ok {
		_spec.SetField(businessexchangerate.FieldMonth, field.TypeTime, value)
		_node.Month = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(businessexchangerate.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RateScaled(); ok {
		_spec.SetField(businessexchangerate.FieldRateScaled, field.TypeInt64, value)
		_node.RateScaled = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(businessexchangerate.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(businessexchangerate.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BusinessExchangeRate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessExchangeRateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BusinessExchangeRateCreate) OnConflict(opts ...sql.ConflictOption) *BusinessExchangeRateUpsertOne {
	_c.conflict = opts
	return &BusinessExchangeRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BusinessExchangeRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BusinessExchangeRateCreate) OnConflictColumns(columns ...string) *BusinessExchangeRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BusinessExchangeRateUpsertOne{
		create: _c,
	}
}

type (
	// BusinessExchangeRateUpsertOne is the builder for "upsert"-ing
	//  one BusinessExchangeRate node.
	BusinessExchangeRateUpsertOne struct {
		create *BusinessExchangeRateCreate
	}

	// BusinessExchangeRateUpsert is the "OnConflict" setter.
	BusinessExchangeRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessExchangeRateUpsert) SetUpdatedAt(v time.Time) *BusinessExchangeRateUpsert {
	u.Set(businessexchangerate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsert) UpdateUpdatedAt() *BusinessExchangeRateUpsert {
	u.SetExcluded(businessexchangerate.FieldUpdatedAt)
	return u
}

// SetMonth sets the "month" field.
func (u *BusinessExchangeRateUpsert) SetMonth(v time.Time) *BusinessExchangeRateUpsert {
	u.Set(businessexchangerate.FieldMonth, v)
	return u
}

// UpdateMonth sets the "month" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsert) UpdateMonth() *BusinessExchangeRateUpsert {
	u.SetExcluded(businessexchangerate.FieldMonth)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BusinessExchangeRateUpsert) SetCurrency(v string) *BusinessExchangeRateUpsert {
	u.Set(businessexchangerate.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsert) UpdateCurrency() *BusinessExchangeRateUpsert {
	u.SetExcluded(businessexchangerate.FieldCurrency)
	return u
}

// SetRateScaled sets the "rate_scaled" field.
func (u *BusinessExchangeRateUpsert) SetRateScaled(v int64) *BusinessExchangeRateUpsert {
	u.Set(businessexchangerate.FieldRateScaled, v)
	return u
}

// UpdateRateScaled sets the "rate_scaled" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsert) UpdateRateScaled() *BusinessExchangeRateUpsert {
	u.SetExcluded(businessexchangerate.FieldRateScaled)
	return u
}

// AddRateScaled adds v to the "rate_scaled" field.
func (u *BusinessExchangeRateUpsert) AddRateScaled(v int64) *BusinessExchangeRateUpsert {
	u.Add(businessexchangerate.FieldRateScaled, v)
	return u
}

// SetSource sets the "source" field.
func (u *BusinessExchangeRateUpsert) SetSource(v string) *BusinessExchangeRateUpsert {
	u.Set(businessexchangerate.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsert) UpdateSource() *BusinessExchangeRateUpsert {
	u.SetExcluded(businessexchangerate.FieldSource)
	return u
}

// SetNotes sets the "notes" field.
func (u *BusinessExchangeRateUpsert) SetNotes(v string) *BusinessExchangeRateUpsert {
	u.Set(businessexchangerate.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsert) UpdateNotes() *BusinessExchangeRateUpsert {
	u.SetExcluded(businessexchangerate.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *BusinessExchangeRateUpsert) ClearNotes() *BusinessExchangeRateUpsert {
	u.SetNull(businessexchangerate.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BusinessExchangeRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BusinessExchangeRateUpsertOne) UpdateNewValues() *BusinessExchangeRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(businessexchangerate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BusinessExchangeRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BusinessExchangeRateUpsertOne) Ignore() *BusinessExchangeRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessExchangeRateUpsertOne) DoNothing() *BusinessExchangeRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessExchangeRateCreate.OnConflict
// documentation for more info.
func (u *BusinessExchangeRateUpsertOne) Update(set func(*BusinessExchangeRateUpsert)) *BusinessExchangeRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessExchangeRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessExchangeRateUpsertOne) SetUpdatedAt(v time.Time) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertOne) UpdateUpdatedAt() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMonth sets the "month" field.
func (u *BusinessExchangeRateUpsertOne) SetMonth(v time.Time) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetMonth(v)
	})
}

// UpdateMonth sets the "month" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertOne) UpdateMonth() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateMonth()
	})
}

// SetCurrency sets the "currency" field.
func (u *BusinessExchangeRateUpsertOne) SetCurrency(v string) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertOne) UpdateCurrency() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateCurrency()
	})
}

// SetRateScaled sets the "rate_scaled" field.
func (u *BusinessExchangeRateUpsertOne) SetRateScaled(v int64) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetRateScaled(v)
	})
}

// AddRateScaled adds v to the "rate_scaled" field.
func (u *BusinessExchangeRateUpsertOne) AddRateScaled(v int64) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.AddRateScaled(v)
	})
}

// UpdateRateScaled sets the "rate_scaled" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertOne) UpdateRateScaled() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateRateScaled()
	})
}

// SetSource sets the "source" field.
func (u *BusinessExchangeRateUpsertOne) SetSource(v string) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertOne) UpdateSource() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateSource()
	})
}

// SetNotes sets the "notes" field.
func (u *BusinessExchangeRateUpsertOne) SetNotes(v string) *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertOne) UpdateNotes() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BusinessExchangeRateUpsertOne) ClearNotes() *BusinessExchangeRateUpsertOne {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *BusinessExchangeRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessExchangeRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessExchangeRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BusinessExchangeRateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BusinessExchangeRateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BusinessExchangeRateCreateBulk is the builder for creating many BusinessExchangeRate entities in bulk.
type BusinessExchangeRateCreateBulk struct {
	config
	err      error
	builders []*BusinessExchangeRateCreate
	conflict []sql.ConflictOption
}

// Save creates the BusinessExchangeRate entities in the database.
func (_c *BusinessExchangeRateCreateBulk) Save(ctx context.Context) ([]*BusinessExchangeRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BusinessExchangeRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BusinessExchangeRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BusinessExchangeRateCreateBulk) SaveX(ctx context.Context) []*BusinessExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BusinessExchangeRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BusinessExchangeRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BusinessExchangeRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessExchangeRateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BusinessExchangeRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *BusinessExchangeRateUpsertBulk {
	_c.conflict = opts
	return &BusinessExchangeRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BusinessExchangeRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BusinessExchangeRateCreateBulk) OnConflictColumns(columns ...string) *BusinessExchangeRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BusinessExchangeRateUpsertBulk{
		create: _c,
	}
}

// BusinessExchangeRateUpsertBulk is the builder for "upsert"-ing
// a bulk of BusinessExchangeRate nodes.
type BusinessExchangeRateUpsertBulk struct {
	create *BusinessExchangeRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BusinessExchangeRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BusinessExchangeRateUpsertBulk) UpdateNewValues() *BusinessExchangeRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(businessexchangerate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BusinessExchangeRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BusinessExchangeRateUpsertBulk) Ignore() *BusinessExchangeRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessExchangeRateUpsertBulk) DoNothing() *BusinessExchangeRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessExchangeRateCreateBulk.OnConflict
// documentation for more info.
func (u *BusinessExchangeRateUpsertBulk) Update(set func(*BusinessExchangeRateUpsert)) *BusinessExchangeRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessExchangeRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessExchangeRateUpsertBulk) SetUpdatedAt(v time.Time) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertBulk) UpdateUpdatedAt() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMonth sets the "month" field.
func (u *BusinessExchangeRateUpsertBulk) SetMonth(v time.Time) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetMonth(v)
	})
}

// UpdateMonth sets the "month" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertBulk) UpdateMonth() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateMonth()
	})
}

// SetCurrency sets the "currency" field.
func (u *BusinessExchangeRateUpsertBulk) SetCurrency(v string) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertBulk) UpdateCurrency() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateCurrency()
	})
}

// SetRateScaled sets the "rate_scaled" field.
func (u *BusinessExchangeRateUpsertBulk) SetRateScaled(v int64) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetRateScaled(v)
	})
}

// AddRateScaled adds v to the "rate_scaled" field.
func (u *BusinessExchangeRateUpsertBulk) AddRateScaled(v int64) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.AddRateScaled(v)
	})
}

// UpdateRateScaled sets the "rate_scaled" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertBulk) UpdateRateScaled() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateRateScaled()
	})
}

// SetSource sets the "source" field.
func (u *BusinessExchangeRateUpsertBulk) SetSource(v string) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertBulk) UpdateSource() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateSource()
	})
}

// SetNotes sets the "notes" field.
func (u *BusinessExchangeRateUpsertBulk) SetNotes(v string) *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BusinessExchangeRateUpsertBulk) UpdateNotes() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BusinessExchangeRateUpsertBulk) ClearNotes() *BusinessExchangeRateUpsertBulk {
	return u.Update(func(s *BusinessExchangeRateUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *BusinessExchangeRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BusinessExchangeRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessExchangeRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessExchangeRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
