// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/businessmonthlysnapshotitem"
)

// BusinessMonthlySnapshotItem is the model entity for the BusinessMonthlySnapshotItem schema.
type BusinessMonthlySnapshotItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SnapshotID holds the value of the "snapshot_id" field.
	SnapshotID int64 `json:"snapshot_id,omitempty"`
	// ItemType holds the value of the "item_type" field.
	ItemType string `json:"item_type,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID *int64 `json:"source_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Category holds the value of the "category" field.
	Category *string `json:"category,omitempty"`
	// Tier holds the value of the "tier" field.
	Tier *string `json:"tier,omitempty"`
	// OriginalAmountMinor holds the value of the "original_amount_minor" field.
	OriginalAmountMinor int64 `json:"original_amount_minor,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RateScaled holds the value of the "rate_scaled" field.
	RateScaled int64 `json:"rate_scaled,omitempty"`
	// AmountCnyCents holds the value of the "amount_cny_cents" field.
	AmountCnyCents int64 `json:"amount_cny_cents,omitempty"`
	// ExpiresOn holds the value of the "expires_on" field.
	ExpiresOn *time.Time `json:"expires_on,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// Included holds the value of the "included" field.
	Included bool `json:"included,omitempty"`
	// LinkedAPIKeyID holds the value of the "linked_api_key_id" field.
	LinkedAPIKeyID *int64 `json:"linked_api_key_id,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName *string `json:"group_name,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail    *string `json:"user_email,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BusinessMonthlySnapshotItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case businessmonthlysnapshotitem.FieldIncluded:
			values[i] = new(sql.NullBool)
		case businessmonthlysnapshotitem.FieldID, businessmonthlysnapshotitem.FieldSnapshotID, businessmonthlysnapshotitem.FieldSourceID, businessmonthlysnapshotitem.FieldOriginalAmountMinor, businessmonthlysnapshotitem.FieldRateScaled, businessmonthlysnapshotitem.FieldAmountCnyCents, businessmonthlysnapshotitem.FieldLinkedAPIKeyID:
			values[i] = new(sql.NullInt64)
		case businessmonthlysnapshotitem.FieldItemType, businessmonthlysnapshotitem.FieldSourceType, businessmonthlysnapshotitem.FieldName, businessmonthlysnapshotitem.FieldCategory, businessmonthlysnapshotitem.FieldTier, businessmonthlysnapshotitem.FieldCurrency, businessmonthlysnapshotitem.FieldReason, businessmonthlysnapshotitem.FieldGroupName, businessmonthlysnapshotitem.FieldUserEmail:
			values[i] = new(sql.NullString)
		case businessmonthlysnapshotitem.FieldCreatedAt, businessmonthlysnapshotitem.FieldUpdatedAt, businessmonthlysnapshotitem.FieldExpiresOn:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BusinessMonthlySnapshotItem fields.
func (_m *BusinessMonthlySnapshotItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case businessmonthlysnapshotitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case businessmonthlysnapshotitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case businessmonthlysnapshotitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case businessmonthlysnapshotitem.FieldSnapshotID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_id", values[i])
			} else if value.Valid {
				_m.SnapshotID = value.Int64
			}
		case businessmonthlysnapshotitem.FieldItemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_type", values[i])
			} else if value.Valid {
				_m.ItemType = value.String
			}
		case businessmonthlysnapshotitem.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case businessmonthlysnapshotitem.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = new(int64)
				*_m.SourceID = value.Int64
			}
		case businessmonthlysnapshotitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case businessmonthlysnapshotitem.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = new(string)
				*_m.Category = value.String
			}
		case businessmonthlysnapshotitem.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = new(string)
				*_m.Tier = value.String
			}
		case businessmonthlysnapshotitem.FieldOriginalAmountMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field original_amount_minor", values[i])
			} else if value.Valid {
				_m.OriginalAmountMinor = value.Int64
			}
		case businessmonthlysnapshotitem.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case businessmonthlysnapshotitem.FieldRateScaled:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_scaled", values[i])
			} else if value.Valid {
				_m.RateScaled = value.Int64
			}
		case businessmonthlysnapshotitem.FieldAmountCnyCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cny_cents", values[i])
			} else if value.Valid {
				_m.AmountCnyCents = value.Int64
			}
		case businessmonthlysnapshotitem.FieldExpiresOn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_on", values[i])
			} else if value.Valid {
				_m.ExpiresOn = new(time.Time)
				*_m.ExpiresOn = value.Time
			}
		case businessmonthlysnapshotitem.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case businessmonthlysnapshotitem.FieldIncluded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field included", values[i])
			} else if value.Valid {
				_m.Included = value.Bool
			}
		case businessmonthlysnapshotitem.FieldLinkedAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field linked_api_key_id", values[i])
			} else if value.Valid {
				_m.LinkedAPIKeyID = new(int64)
				*_m.LinkedAPIKeyID = value.Int64
			}
		case businessmonthlysnapshotitem.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = new(string)
				*_m.GroupName = value.String
			}
		case businessmonthlysnapshotitem.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = new(string)
				*_m.UserEmail = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BusinessMonthlySnapshotItem.
// This includes values selected through modifiers, order, etc.
func (_m *BusinessMonthlySnapshotItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BusinessMonthlySnapshotItem.
// Note that you need to call BusinessMonthlySnapshotItem.Unwrap() before calling this method if this BusinessMonthlySnapshotItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BusinessMonthlySnapshotItem) Update() *BusinessMonthlySnapshotItemUpdateOne {
	return NewBusinessMonthlySnapshotItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BusinessMonthlySnapshotItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BusinessMonthlySnapshotItem) Unwrap() *BusinessMonthlySnapshotItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BusinessMonthlySnapshotItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BusinessMonthlySnapshotItem) String() string {
	var builder strings.Builder
	builder.WriteString("BusinessMonthlySnapshotItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("snapshot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SnapshotID))
	builder.WriteString(", ")
	builder.WriteString("item_type=")
	builder.WriteString(_m.ItemType)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	if v := _m.SourceID; v != nil {
		builder.WriteString("source_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Category; v != nil {
		builder.WriteString("category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Tier; v != nil {
		builder.WriteString("tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("original_amount_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginalAmountMinor))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("rate_scaled=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateScaled))
	builder.WriteString(", ")
	builder.WriteString("amount_cny_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCnyCents))
	builder.WriteString(", ")
	if v := _m.ExpiresOn; v != nil {
		builder.WriteString("expires_on=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("included=")
	builder.WriteString(fmt.Sprintf("%v", _m.Included))
	builder.WriteString(", ")
	if v := _m.LinkedAPIKeyID; v != nil {
		builder.WriteString("linked_api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupName; v != nil {
		builder.WriteString("group_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserEmail; v != nil {
		builder.WriteString("user_email=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BusinessMonthlySnapshotItems is a parsable slice of BusinessMonthlySnapshotItem.
type BusinessMonthlySnapshotItems []*BusinessMonthlySnapshotItem
