// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businesscostitem"
)

// BusinessCostItemCreate is the builder for creating a BusinessCostItem entity.
type BusinessCostItemCreate struct {
	config
	mutation *BusinessCostItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BusinessCostItemCreate) SetCreatedAt(v time.Time) *BusinessCostItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableCreatedAt(v *time.Time) *BusinessCostItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BusinessCostItemCreate) SetUpdatedAt(v time.Time) *BusinessCostItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableUpdatedAt(v *time.Time) *BusinessCostItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BusinessCostItemCreate) SetDeletedAt(v time.Time) *BusinessCostItemCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableDeletedAt(v *time.Time) *BusinessCostItemCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *BusinessCostItemCreate) SetName(v string) *BusinessCostItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCostClass sets the "cost_class" field.
func (_c *BusinessCostItemCreate) SetCostClass(v string) *BusinessCostItemCreate {
	_c.mutation.SetCostClass(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *BusinessCostItemCreate) SetCategory(v string) *BusinessCostItemCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetAmountMinor sets the "amount_minor" field.
func (_c *BusinessCostItemCreate) SetAmountMinor(v int64) *BusinessCostItemCreate {
	_c.mutation.SetAmountMinor(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BusinessCostItemCreate) SetCurrency(v string) *BusinessCostItemCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetBillingCycle sets the "billing_cycle" field.
func (_c *BusinessCostItemCreate) SetBillingCycle(v string) *BusinessCostItemCreate {
	_c.mutation.SetBillingCycle(v)
	return _c
}

// SetStartsOn sets the "starts_on" field.
func (_c *BusinessCostItemCreate) SetStartsOn(v time.Time) *BusinessCostItemCreate {
	_c.mutation.SetStartsOn(v)
	return _c
}

// SetEndsOn sets the "ends_on" field.
func (_c *BusinessCostItemCreate) SetEndsOn(v time.Time) *BusinessCostItemCreate {
	_c.mutation.SetEndsOn(v)
	return _c
}

// SetNillableEndsOn sets the "ends_on" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableEndsOn(v *time.Time) *BusinessCostItemCreate {
	if v != nil {
		_c.SetEndsOn(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *BusinessCostItemCreate) SetAccountID(v int64) *BusinessCostItemCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableAccountID(v *int64) *BusinessCostItemCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetAccountIdentifier sets the "account_identifier" field.
func (_c *BusinessCostItemCreate) SetAccountIdentifier(v string) *BusinessCostItemCreate {
	_c.mutation.SetAccountIdentifier(v)
	return _c
}

// SetNillableAccountIdentifier sets the "account_identifier" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableAccountIdentifier(v *string) *BusinessCostItemCreate {
	if v != nil {
		_c.SetAccountIdentifier(*v)
	}
	return _c
}

// SetIsFree sets the "is_free" field.
func (_c *BusinessCostItemCreate) SetIsFree(v bool) *BusinessCostItemCreate {
	_c.mutation.SetIsFree(v)
	return _c
}

// SetNillableIsFree sets the "is_free" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableIsFree(v *bool) *BusinessCostItemCreate {
	if v != nil {
		_c.SetIsFree(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *BusinessCostItemCreate) SetActive(v bool) *BusinessCostItemCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableActive(v *bool) *BusinessCostItemCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *BusinessCostItemCreate) SetNotes(v string) *BusinessCostItemCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *BusinessCostItemCreate) SetNillableNotes(v *string) *BusinessCostItemCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// Mutation returns the BusinessCostItemMutation object of the builder.
func (_c *BusinessCostItemCreate) Mutation() *BusinessCostItemMutation {
	return _c.mutation
}

// Save creates the BusinessCostItem in the database.
func (_c *BusinessCostItemCreate) Save(ctx context.Context) (*BusinessCostItem, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BusinessCostItemCreate) SaveX(ctx context.Context) *BusinessCostItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BusinessCostItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BusinessCostItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BusinessCostItemCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if businesscostitem.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized businesscostitem.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := businesscostitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if businesscostitem.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized businesscostitem.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := businesscostitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsFree(); !ok {
		v := businesscostitem.DefaultIsFree
		_c.mutation.SetIsFree(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := businesscostitem.DefaultActive
		_c.mutation.SetActive(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BusinessCostItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BusinessCostItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BusinessCostItem.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BusinessCostItem.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := businesscostitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostClass(); !ok {
		return &ValidationError{Name: "cost_class", err: errors.New(`ent: missing required field "BusinessCostItem.cost_class"`)}
	}
	if v, ok := _c.mutation.CostClass(); ok {
		if err := businesscostitem.CostClassValidator(v); err != nil {
			return &ValidationError{Name: "cost_class", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.cost_class": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "BusinessCostItem.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := businesscostitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountMinor(); !ok {
		return &ValidationError{Name: "amount_minor", err: errors.New(`ent: missing required field "BusinessCostItem.amount_minor"`)}
	}
	if v, ok := _c.mutation.AmountMinor(); ok {
		if err := businesscostitem.AmountMinorValidator(v); err != nil {
			return &ValidationError{Name: "amount_minor", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.amount_minor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BusinessCostItem.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := businesscostitem.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingCycle(); !ok {
		return &ValidationError{Name: "billing_cycle", err: errors.New(`ent: missing required field "BusinessCostItem.billing_cycle"`)}
	}
	if v, ok := _c.mutation.BillingCycle(); ok {
		if err := businesscostitem.BillingCycleValidator(v); err != nil {
			return &ValidationError{Name: "billing_cycle", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.billing_cycle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsOn(); !ok {
		return &ValidationError{Name: "starts_on", err: errors.New(`ent: missing required field "BusinessCostItem.starts_on"`)}
	}
	if v, ok := _c.mutation.AccountIdentifier(); ok {
		if err := businesscostitem.AccountIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "account_identifier", err: fmt.Errorf(`ent: validator failed for field "BusinessCostItem.account_identifier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsFree(); !ok {
		return &ValidationError{Name: "is_free", err: errors.New(`ent: missing required field "BusinessCostItem.is_free"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "BusinessCostItem.active"`)}
	}
	return nil
}

func (_c *BusinessCostItemCreate) sqlSave(ctx context.Context) (*BusinessCostItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BusinessCostItemCreate) createSpec() (*BusinessCostItem, *sqlgraph.CreateSpec) {
	var (
		_node = &BusinessCostItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(businesscostitem.Table, sqlgraph.NewFieldSpec(businesscostitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(businesscostitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(businesscostitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(businesscostitem.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(businesscostitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CostClass(); ok {
		_spec.SetField(businesscostitem.FieldCostClass, field.TypeString, value)
		_node.CostClass = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(businesscostitem.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.AmountMinor(); ok {
		_spec.SetField(businesscostitem.FieldAmountMinor, field.TypeInt64, value)
		_node.AmountMinor = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(businesscostitem.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.BillingCycle(); ok {
		_spec.SetField(businesscostitem.FieldBillingCycle, field.TypeString, value)
		_node.BillingCycle = value
	}
	if value, ok := _c.mutation.StartsOn(); ok {
		_spec.SetField(businesscostitem.FieldStartsOn, field.TypeTime, value)
		_node.StartsOn = value
	}
	if value, ok := _c.mutation.EndsOn(); ok {
		_spec.SetField(businesscostitem.FieldEndsOn, field.TypeTime, value)
		_node.EndsOn = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(businesscostitem.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.AccountIdentifier(); ok {
		_spec.SetField(businesscostitem.FieldAccountIdentifier, field.TypeString, value)
		_node.AccountIdentifier = &value
	}
	if value, ok := _c.mutation.IsFree(); ok {
		_spec.SetField(businesscostitem.FieldIsFree, field.TypeBool, value)
		_node.IsFree = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(businesscostitem.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(businesscostitem.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BusinessCostItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessCostItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BusinessCostItemCreate) OnConflict(opts ...sql.ConflictOption) *BusinessCostItemUpsertOne {
	_c.conflict = opts
	return &BusinessCostItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BusinessCostItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BusinessCostItemCreate) OnConflictColumns(columns ...string) *BusinessCostItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BusinessCostItemUpsertOne{
		create: _c,
	}
}

type (
	// BusinessCostItemUpsertOne is the builder for "upsert"-ing
	//  one BusinessCostItem node.
	BusinessCostItemUpsertOne struct {
		create *BusinessCostItemCreate
	}

	// BusinessCostItemUpsert is the "OnConflict" setter.
	BusinessCostItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessCostItemUpsert) SetUpdatedAt(v time.Time) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateUpdatedAt() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BusinessCostItemUpsert) SetDeletedAt(v time.Time) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateDeletedAt() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BusinessCostItemUpsert) ClearDeletedAt() *BusinessCostItemUpsert {
	u.SetNull(businesscostitem.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *BusinessCostItemUpsert) SetName(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateName() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldName)
	return u
}

// SetCostClass sets the "cost_class" field.
func (u *BusinessCostItemUpsert) SetCostClass(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldCostClass, v)
	return u
}

// UpdateCostClass sets the "cost_class" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateCostClass() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldCostClass)
	return u
}

// SetCategory sets the "category" field.
func (u *BusinessCostItemUpsert) SetCategory(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateCategory() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldCategory)
	return u
}

// SetAmountMinor sets the "amount_minor" field.
func (u *BusinessCostItemUpsert) SetAmountMinor(v int64) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldAmountMinor, v)
	return u
}

// UpdateAmountMinor sets the "amount_minor" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateAmountMinor() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldAmountMinor)
	return u
}

// AddAmountMinor adds v to the "amount_minor" field.
func (u *BusinessCostItemUpsert) AddAmountMinor(v int64) *BusinessCostItemUpsert {
	u.Add(businesscostitem.FieldAmountMinor, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BusinessCostItemUpsert) SetCurrency(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateCurrency() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldCurrency)
	return u
}

// SetBillingCycle sets the "billing_cycle" field.
func (u *BusinessCostItemUpsert) SetBillingCycle(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldBillingCycle, v)
	return u
}

// UpdateBillingCycle sets the "billing_cycle" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateBillingCycle() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldBillingCycle)
	return u
}

// SetStartsOn sets the "starts_on" field.
func (u *BusinessCostItemUpsert) SetStartsOn(v time.Time) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldStartsOn, v)
	return u
}

// UpdateStartsOn sets the "starts_on" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateStartsOn() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldStartsOn)
	return u
}

// SetEndsOn sets the "ends_on" field.
func (u *BusinessCostItemUpsert) SetEndsOn(v time.Time) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldEndsOn, v)
	return u
}

// UpdateEndsOn sets the "ends_on" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateEndsOn() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldEndsOn)
	return u
}

// ClearEndsOn clears the value of the "ends_on" field.
func (u *BusinessCostItemUpsert) ClearEndsOn() *BusinessCostItemUpsert {
	u.SetNull(businesscostitem.FieldEndsOn)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *BusinessCostItemUpsert) SetAccountID(v int64) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateAccountID() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *BusinessCostItemUpsert) AddAccountID(v int64) *BusinessCostItemUpsert {
	u.Add(businesscostitem.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *BusinessCostItemUpsert) ClearAccountID() *BusinessCostItemUpsert {
	u.SetNull(businesscostitem.FieldAccountID)
	return u
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *BusinessCostItemUpsert) SetAccountIdentifier(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldAccountIdentifier, v)
	return u
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateAccountIdentifier() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldAccountIdentifier)
	return u
}

// ClearAccountIdentifier clears the value of the "account_identifier" field.
func (u *BusinessCostItemUpsert) ClearAccountIdentifier() *BusinessCostItemUpsert {
	u.SetNull(businesscostitem.FieldAccountIdentifier)
	return u
}

// SetIsFree sets the "is_free" field.
func (u *BusinessCostItemUpsert) SetIsFree(v bool) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldIsFree, v)
	return u
}

// UpdateIsFree sets the "is_free" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateIsFree() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldIsFree)
	return u
}

// SetActive sets the "active" field.
func (u *BusinessCostItemUpsert) SetActive(v bool) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateActive() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldActive)
	return u
}

// SetNotes sets the "notes" field.
func (u *BusinessCostItemUpsert) SetNotes(v string) *BusinessCostItemUpsert {
	u.Set(businesscostitem.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BusinessCostItemUpsert) UpdateNotes() *BusinessCostItemUpsert {
	u.SetExcluded(businesscostitem.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *BusinessCostItemUpsert) ClearNotes() *BusinessCostItemUpsert {
	u.SetNull(businesscostitem.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BusinessCostItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BusinessCostItemUpsertOne) UpdateNewValues() *BusinessCostItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(businesscostitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BusinessCostItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BusinessCostItemUpsertOne) Ignore() *BusinessCostItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessCostItemUpsertOne) DoNothing() *BusinessCostItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessCostItemCreate.OnConflict
// documentation for more info.
func (u *BusinessCostItemUpsertOne) Update(set func(*BusinessCostItemUpsert)) *BusinessCostItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessCostItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessCostItemUpsertOne) SetUpdatedAt(v time.Time) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateUpdatedAt() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BusinessCostItemUpsertOne) SetDeletedAt(v time.Time) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateDeletedAt() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BusinessCostItemUpsertOne) ClearDeletedAt() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *BusinessCostItemUpsertOne) SetName(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateName() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateName()
	})
}

// SetCostClass sets the "cost_class" field.
func (u *BusinessCostItemUpsertOne) SetCostClass(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetCostClass(v)
	})
}

// UpdateCostClass sets the "cost_class" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateCostClass() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateCostClass()
	})
}

// SetCategory sets the "category" field.
func (u *BusinessCostItemUpsertOne) SetCategory(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateCategory() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateCategory()
	})
}

// SetAmountMinor sets the "amount_minor" field.
func (u *BusinessCostItemUpsertOne) SetAmountMinor(v int64) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetAmountMinor(v)
	})
}

// AddAmountMinor adds v to the "amount_minor" field.
func (u *BusinessCostItemUpsertOne) AddAmountMinor(v int64) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.AddAmountMinor(v)
	})
}

// UpdateAmountMinor sets the "amount_minor" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateAmountMinor() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateAmountMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *BusinessCostItemUpsertOne) SetCurrency(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateCurrency() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateCurrency()
	})
}

// SetBillingCycle sets the "billing_cycle" field.
func (u *BusinessCostItemUpsertOne) SetBillingCycle(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetBillingCycle(v)
	})
}

// UpdateBillingCycle sets the "billing_cycle" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateBillingCycle() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateBillingCycle()
	})
}

// SetStartsOn sets the "starts_on" field.
func (u *BusinessCostItemUpsertOne) SetStartsOn(v time.Time) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetStartsOn(v)
	})
}

// UpdateStartsOn sets the "starts_on" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateStartsOn() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateStartsOn()
	})
}

// SetEndsOn sets the "ends_on" field.
func (u *BusinessCostItemUpsertOne) SetEndsOn(v time.Time) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetEndsOn(v)
	})
}

// UpdateEndsOn sets the "ends_on" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateEndsOn() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateEndsOn()
	})
}

// ClearEndsOn clears the value of the "ends_on" field.
func (u *BusinessCostItemUpsertOne) ClearEndsOn() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearEndsOn()
	})
}

// SetAccountID sets the "account_id" field.
func (u *BusinessCostItemUpsertOne) SetAccountID(v int64) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *BusinessCostItemUpsertOne) AddAccountID(v int64) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateAccountID() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *BusinessCostItemUpsertOne) ClearAccountID() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearAccountID()
	})
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *BusinessCostItemUpsertOne) SetAccountIdentifier(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetAccountIdentifier(v)
	})
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateAccountIdentifier() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateAccountIdentifier()
	})
}

// ClearAccountIdentifier clears the value of the "account_identifier" field.
func (u *BusinessCostItemUpsertOne) ClearAccountIdentifier() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearAccountIdentifier()
	})
}

// SetIsFree sets the "is_free" field.
func (u *BusinessCostItemUpsertOne) SetIsFree(v bool) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetIsFree(v)
	})
}

// UpdateIsFree sets the "is_free" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateIsFree() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateIsFree()
	})
}

// SetActive sets the "active" field.
func (u *BusinessCostItemUpsertOne) SetActive(v bool) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateActive() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateActive()
	})
}

// SetNotes sets the "notes" field.
func (u *BusinessCostItemUpsertOne) SetNotes(v string) *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BusinessCostItemUpsertOne) UpdateNotes() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BusinessCostItemUpsertOne) ClearNotes() *BusinessCostItemUpsertOne {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *BusinessCostItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessCostItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessCostItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BusinessCostItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BusinessCostItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BusinessCostItemCreateBulk is the builder for creating many BusinessCostItem entities in bulk.
type BusinessCostItemCreateBulk struct {
	config
	err      error
	builders []*BusinessCostItemCreate
	conflict []sql.ConflictOption
}

// Save creates the BusinessCostItem entities in the database.
func (_c *BusinessCostItemCreateBulk) Save(ctx context.Context) ([]*BusinessCostItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BusinessCostItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BusinessCostItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BusinessCostItemCreateBulk) SaveX(ctx context.Context) []*BusinessCostItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BusinessCostItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BusinessCostItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BusinessCostItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessCostItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BusinessCostItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *BusinessCostItemUpsertBulk {
	_c.conflict = opts
	return &BusinessCostItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BusinessCostItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BusinessCostItemCreateBulk) OnConflictColumns(columns ...string) *BusinessCostItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BusinessCostItemUpsertBulk{
		create: _c,
	}
}

// BusinessCostItemUpsertBulk is the builder for "upsert"-ing
// a bulk of BusinessCostItem nodes.
type BusinessCostItemUpsertBulk struct {
	create *BusinessCostItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BusinessCostItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BusinessCostItemUpsertBulk) UpdateNewValues() *BusinessCostItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(businesscostitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BusinessCostItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BusinessCostItemUpsertBulk) Ignore() *BusinessCostItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessCostItemUpsertBulk) DoNothing() *BusinessCostItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessCostItemCreateBulk.OnConflict
// documentation for more info.
func (u *BusinessCostItemUpsertBulk) Update(set func(*BusinessCostItemUpsert)) *BusinessCostItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessCostItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessCostItemUpsertBulk) SetUpdatedAt(v time.Time) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateUpdatedAt() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BusinessCostItemUpsertBulk) SetDeletedAt(v time.Time) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateDeletedAt() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BusinessCostItemUpsertBulk) ClearDeletedAt() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *BusinessCostItemUpsertBulk) SetName(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateName() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateName()
	})
}

// SetCostClass sets the "cost_class" field.
func (u *BusinessCostItemUpsertBulk) SetCostClass(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetCostClass(v)
	})
}

// UpdateCostClass sets the "cost_class" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateCostClass() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateCostClass()
	})
}

// SetCategory sets the "category" field.
func (u *BusinessCostItemUpsertBulk) SetCategory(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateCategory() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateCategory()
	})
}

// SetAmountMinor sets the "amount_minor" field.
func (u *BusinessCostItemUpsertBulk) SetAmountMinor(v int64) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetAmountMinor(v)
	})
}

// AddAmountMinor adds v to the "amount_minor" field.
func (u *BusinessCostItemUpsertBulk) AddAmountMinor(v int64) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.AddAmountMinor(v)
	})
}

// UpdateAmountMinor sets the "amount_minor" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateAmountMinor() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateAmountMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *BusinessCostItemUpsertBulk) SetCurrency(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateCurrency() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateCurrency()
	})
}

// SetBillingCycle sets the "billing_cycle" field.
func (u *BusinessCostItemUpsertBulk) SetBillingCycle(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetBillingCycle(v)
	})
}

// UpdateBillingCycle sets the "billing_cycle" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateBillingCycle() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateBillingCycle()
	})
}

// SetStartsOn sets the "starts_on" field.
func (u *BusinessCostItemUpsertBulk) SetStartsOn(v time.Time) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetStartsOn(v)
	})
}

// UpdateStartsOn sets the "starts_on" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateStartsOn() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateStartsOn()
	})
}

// SetEndsOn sets the "ends_on" field.
func (u *BusinessCostItemUpsertBulk) SetEndsOn(v time.Time) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetEndsOn(v)
	})
}

// UpdateEndsOn sets the "ends_on" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateEndsOn() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateEndsOn()
	})
}

// ClearEndsOn clears the value of the "ends_on" field.
func (u *BusinessCostItemUpsertBulk) ClearEndsOn() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearEndsOn()
	})
}

// SetAccountID sets the "account_id" field.
func (u *BusinessCostItemUpsertBulk) SetAccountID(v int64) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *BusinessCostItemUpsertBulk) AddAccountID(v int64) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateAccountID() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *BusinessCostItemUpsertBulk) ClearAccountID() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearAccountID()
	})
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *BusinessCostItemUpsertBulk) SetAccountIdentifier(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetAccountIdentifier(v)
	})
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateAccountIdentifier() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateAccountIdentifier()
	})
}

// ClearAccountIdentifier clears the value of the "account_identifier" field.
func (u *BusinessCostItemUpsertBulk) ClearAccountIdentifier() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearAccountIdentifier()
	})
}

// SetIsFree sets the "is_free" field.
func (u *BusinessCostItemUpsertBulk) SetIsFree(v bool) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetIsFree(v)
	})
}

// UpdateIsFree sets the "is_free" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateIsFree() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateIsFree()
	})
}

// SetActive sets the "active" field.
func (u *BusinessCostItemUpsertBulk) SetActive(v bool) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateActive() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateActive()
	})
}

// SetNotes sets the "notes" field.
func (u *BusinessCostItemUpsertBulk) SetNotes(v string) *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BusinessCostItemUpsertBulk) UpdateNotes() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BusinessCostItemUpsertBulk) ClearNotes() *BusinessCostItemUpsertBulk {
	return u.Update(func(s *BusinessCostItemUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *BusinessCostItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BusinessCostItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessCostItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessCostItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
