// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessmonthlysnapshotitem"
)

// BusinessMonthlySnapshotItemCreate is the builder for creating a BusinessMonthlySnapshotItem entity.
type BusinessMonthlySnapshotItemCreate struct {
	config
	mutation *BusinessMonthlySnapshotItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetCreatedAt(v time.Time) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableCreatedAt(v *time.Time) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetUpdatedAt(v time.Time) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableUpdatedAt(v *time.Time) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot_id" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetSnapshotID(v int64) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetSnapshotID(v)
	return _c
}

// SetItemType sets the "item_type" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetItemType(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetItemType(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetSourceType(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetSourceID(v int64) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableSourceID(v *int64) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetName(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetCategory(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableCategory(v *string) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetTier sets the "tier" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetTier(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableTier(v *string) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetTier(*v)
	}
	return _c
}

// SetOriginalAmountMinor sets the "original_amount_minor" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetOriginalAmountMinor(v)
	return _c
}

// SetNillableOriginalAmountMinor sets the "original_amount_minor" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableOriginalAmountMinor(v *int64) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetOriginalAmountMinor(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetCurrency(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetRateScaled sets the "rate_scaled" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetRateScaled(v int64) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetRateScaled(v)
	return _c
}

// SetNillableRateScaled sets the "rate_scaled" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableRateScaled(v *int64) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetRateScaled(*v)
	}
	return _c
}

// SetAmountCnyCents sets the "amount_cny_cents" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetAmountCnyCents(v int64) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetAmountCnyCents(v)
	return _c
}

// SetNillableAmountCnyCents sets the "amount_cny_cents" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableAmountCnyCents(v *int64) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetAmountCnyCents(*v)
	}
	return _c
}

// SetExpiresOn sets the "expires_on" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetExpiresOn(v time.Time) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetExpiresOn(v)
	return _c
}

// SetNillableExpiresOn sets the "expires_on" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableExpiresOn(v *time.Time) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetExpiresOn(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetReason(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableReason(v *string) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetIncluded sets the "included" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetIncluded(v bool) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetIncluded(v)
	return _c
}

// SetNillableIncluded sets the "included" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableIncluded(v *bool) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetIncluded(*v)
	}
	return _c
}

// SetLinkedAPIKeyID sets the "linked_api_key_id" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetLinkedAPIKeyID(v)
	return _c
}

// SetNillableLinkedAPIKeyID sets the "linked_api_key_id" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableLinkedAPIKeyID(v *int64) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetLinkedAPIKeyID(*v)
	}
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetGroupName(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableGroupName(v *string) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *BusinessMonthlySnapshotItemCreate) SetUserEmail(v string) *BusinessMonthlySnapshotItemCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *BusinessMonthlySnapshotItemCreate) SetNillableUserEmail(v *string) *BusinessMonthlySnapshotItemCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// Mutation returns the BusinessMonthlySnapshotItemMutation object of the builder.
func (_c *BusinessMonthlySnapshotItemCreate) Mutation() *BusinessMonthlySnapshotItemMutation {
	return _c.mutation
}

// Save creates the BusinessMonthlySnapshotItem in the database.
func (_c *BusinessMonthlySnapshotItemCreate) Save(ctx context.Context) (*BusinessMonthlySnapshotItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BusinessMonthlySnapshotItemCreate) SaveX(ctx context.Context) *BusinessMonthlySnapshotItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BusinessMonthlySnapshotItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BusinessMonthlySnapshotItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BusinessMonthlySnapshotItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := businessmonthlysnapshotitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := businessmonthlysnapshotitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.OriginalAmountMinor(); !ok {
		v := businessmonthlysnapshotitem.DefaultOriginalAmountMinor
		_c.mutation.SetOriginalAmountMinor(v)
	}
	if _, ok := _c.mutation.RateScaled(); !ok {
		v := businessmonthlysnapshotitem.DefaultRateScaled
		_c.mutation.SetRateScaled(v)
	}
	if _, ok := _c.mutation.AmountCnyCents(); !ok {
		v := businessmonthlysnapshotitem.DefaultAmountCnyCents
		_c.mutation.SetAmountCnyCents(v)
	}
	if _, ok := _c.mutation.Included(); !ok {
		v := businessmonthlysnapshotitem.DefaultIncluded
		_c.mutation.SetIncluded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BusinessMonthlySnapshotItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.updated_at"`)}
	}
	if _, ok := _c.mutation.SnapshotID(); !ok {
		return &ValidationError{Name: "snapshot_id", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.snapshot_id"`)}
	}
	if _, ok := _c.mutation.ItemType(); !ok {
		return &ValidationError{Name: "item_type", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.item_type"`)}
	}
	if v, ok := _c.mutation.ItemType(); ok {
		if err := businessmonthlysnapshotitem.ItemTypeValidator(v); err != nil {
			return &ValidationError{Name: "item_type", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.item_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := businessmonthlysnapshotitem.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := businessmonthlysnapshotitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := businessmonthlysnapshotitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Tier(); ok {
		if err := businessmonthlysnapshotitem.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalAmountMinor(); !ok {
		return &ValidationError{Name: "original_amount_minor", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.original_amount_minor"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := businessmonthlysnapshotitem.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateScaled(); !ok {
		return &ValidationError{Name: "rate_scaled", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.rate_scaled"`)}
	}
	if v, ok := _c.mutation.RateScaled(); ok {
		if err := businessmonthlysnapshotitem.RateScaledValidator(v); err != nil {
			return &ValidationError{Name: "rate_scaled", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.rate_scaled": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountCnyCents(); !ok {
		return &ValidationError{Name: "amount_cny_cents", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.amount_cny_cents"`)}
	}
	if _, ok := _c.mutation.Included(); !ok {
		return &ValidationError{Name: "included", err: errors.New(`ent: missing required field "BusinessMonthlySnapshotItem.included"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := businessmonthlysnapshotitem.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.group_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := businessmonthlysnapshotitem.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.user_email": %w`, err)}
		}
	}
	return nil
}

func (_c *BusinessMonthlySnapshotItemCreate) sqlSave(ctx context.Context) (*BusinessMonthlySnapshotItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BusinessMonthlySnapshotItemCreate) createSpec() (*BusinessMonthlySnapshotItem, *sqlgraph.CreateSpec) {
	var (
		_node = &BusinessMonthlySnapshotItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(businessmonthlysnapshotitem.Table, sqlgraph.NewFieldSpec(businessmonthlysnapshotitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SnapshotID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSnapshotID, field.TypeInt64, value)
		_node.SnapshotID = value
	}
	if value, ok := _c.mutation.ItemType(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldItemType, field.TypeString, value)
		_node.ItemType = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64, value)
		_node.SourceID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCategory, field.TypeString, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldTier, field.TypeString, value)
		_node.Tier = &value
	}
	if value, ok := _c.mutation.OriginalAmountMinor(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldOriginalAmountMinor, field.TypeInt64, value)
		_node.OriginalAmountMinor = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RateScaled(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldRateScaled, field.TypeInt64, value)
		_node.RateScaled = value
	}
	if value, ok := _c.mutation.AmountCnyCents(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldAmountCnyCents, field.TypeInt64, value)
		_node.AmountCnyCents = value
	}
	if value, ok := _c.mutation.ExpiresOn(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldExpiresOn, field.TypeTime, value)
		_node.ExpiresOn = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Included(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldIncluded, field.TypeBool, value)
		_node.Included = value
	}
	if value, ok := _c.mutation.LinkedAPIKeyID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64, value)
		_node.LinkedAPIKeyID = &value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldGroupName, field.TypeString, value)
		_node.GroupName = &value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BusinessMonthlySnapshotItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessMonthlySnapshotItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BusinessMonthlySnapshotItemCreate) OnConflict(opts ...sql.ConflictOption) *BusinessMonthlySnapshotItemUpsertOne {
	_c.conflict = opts
	return &BusinessMonthlySnapshotItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BusinessMonthlySnapshotItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BusinessMonthlySnapshotItemCreate) OnConflictColumns(columns ...string) *BusinessMonthlySnapshotItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BusinessMonthlySnapshotItemUpsertOne{
		create: _c,
	}
}

type (
	// BusinessMonthlySnapshotItemUpsertOne is the builder for "upsert"-ing
	//  one BusinessMonthlySnapshotItem node.
	BusinessMonthlySnapshotItemUpsertOne struct {
		create *BusinessMonthlySnapshotItemCreate
	}

	// BusinessMonthlySnapshotItemUpsert is the "OnConflict" setter.
	BusinessMonthlySnapshotItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetUpdatedAt(v time.Time) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateUpdatedAt() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldUpdatedAt)
	return u
}

// SetSnapshotID sets the "snapshot_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetSnapshotID(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldSnapshotID, v)
	return u
}

// UpdateSnapshotID sets the "snapshot_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateSnapshotID() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldSnapshotID)
	return u
}

// AddSnapshotID adds v to the "snapshot_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) AddSnapshotID(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Add(businessmonthlysnapshotitem.FieldSnapshotID, v)
	return u
}

// SetItemType sets the "item_type" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetItemType(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldItemType, v)
	return u
}

// UpdateItemType sets the "item_type" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateItemType() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldItemType)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetSourceType(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateSourceType() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetSourceID(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateSourceID() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) AddSourceID(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Add(businessmonthlysnapshotitem.FieldSourceID, v)
	return u
}

// ClearSourceID clears the value of the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearSourceID() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldSourceID)
	return u
}

// SetName sets the "name" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetName(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateName() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldName)
	return u
}

// SetCategory sets the "category" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetCategory(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateCategory() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldCategory)
	return u
}

// ClearCategory clears the value of the "category" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearCategory() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldCategory)
	return u
}

// SetTier sets the "tier" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetTier(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateTier() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldTier)
	return u
}

// ClearTier clears the value of the "tier" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearTier() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldTier)
	return u
}

// SetOriginalAmountMinor sets the "original_amount_minor" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldOriginalAmountMinor, v)
	return u
}

// UpdateOriginalAmountMinor sets the "original_amount_minor" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateOriginalAmountMinor() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldOriginalAmountMinor)
	return u
}

// AddOriginalAmountMinor adds v to the "original_amount_minor" field.
func (u *BusinessMonthlySnapshotItemUpsert) AddOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Add(businessmonthlysnapshotitem.FieldOriginalAmountMinor, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetCurrency(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateCurrency() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldCurrency)
	return u
}

// SetRateScaled sets the "rate_scaled" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetRateScaled(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldRateScaled, v)
	return u
}

// UpdateRateScaled sets the "rate_scaled" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateRateScaled() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldRateScaled)
	return u
}

// AddRateScaled adds v to the "rate_scaled" field.
func (u *BusinessMonthlySnapshotItemUpsert) AddRateScaled(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Add(businessmonthlysnapshotitem.FieldRateScaled, v)
	return u
}

// SetAmountCnyCents sets the "amount_cny_cents" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldAmountCnyCents, v)
	return u
}

// UpdateAmountCnyCents sets the "amount_cny_cents" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateAmountCnyCents() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldAmountCnyCents)
	return u
}

// AddAmountCnyCents adds v to the "amount_cny_cents" field.
func (u *BusinessMonthlySnapshotItemUpsert) AddAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Add(businessmonthlysnapshotitem.FieldAmountCnyCents, v)
	return u
}

// SetExpiresOn sets the "expires_on" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetExpiresOn(v time.Time) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldExpiresOn, v)
	return u
}

// UpdateExpiresOn sets the "expires_on" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateExpiresOn() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldExpiresOn)
	return u
}

// ClearExpiresOn clears the value of the "expires_on" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearExpiresOn() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldExpiresOn)
	return u
}

// SetReason sets the "reason" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetReason(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateReason() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearReason() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldReason)
	return u
}

// SetIncluded sets the "included" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetIncluded(v bool) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldIncluded, v)
	return u
}

// UpdateIncluded sets the "included" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateIncluded() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldIncluded)
	return u
}

// SetLinkedAPIKeyID sets the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, v)
	return u
}

// UpdateLinkedAPIKeyID sets the "linked_api_key_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldLinkedAPIKeyID)
	return u
}

// AddLinkedAPIKeyID adds v to the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) AddLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpsert {
	u.Add(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, v)
	return u
}

// ClearLinkedAPIKeyID clears the value of the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldLinkedAPIKeyID)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetGroupName(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateGroupName() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldGroupName)
	return u
}

// ClearGroupName clears the value of the "group_name" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearGroupName() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldGroupName)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *BusinessMonthlySnapshotItemUpsert) SetUserEmail(v string) *BusinessMonthlySnapshotItemUpsert {
	u.Set(businessmonthlysnapshotitem.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsert) UpdateUserEmail() *BusinessMonthlySnapshotItemUpsert {
	u.SetExcluded(businessmonthlysnapshotitem.FieldUserEmail)
	return u
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *BusinessMonthlySnapshotItemUpsert) ClearUserEmail() *BusinessMonthlySnapshotItemUpsert {
	u.SetNull(businessmonthlysnapshotitem.FieldUserEmail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BusinessMonthlySnapshotItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateNewValues() *BusinessMonthlySnapshotItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(businessmonthlysnapshotitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BusinessMonthlySnapshotItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BusinessMonthlySnapshotItemUpsertOne) Ignore() *BusinessMonthlySnapshotItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessMonthlySnapshotItemUpsertOne) DoNothing() *BusinessMonthlySnapshotItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessMonthlySnapshotItemCreate.OnConflict
// documentation for more info.
func (u *BusinessMonthlySnapshotItemUpsertOne) Update(set func(*BusinessMonthlySnapshotItemUpsert)) *BusinessMonthlySnapshotItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessMonthlySnapshotItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetUpdatedAt(v time.Time) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateUpdatedAt() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSnapshotID sets the "snapshot_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetSnapshotID(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetSnapshotID(v)
	})
}

// AddSnapshotID adds v to the "snapshot_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) AddSnapshotID(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddSnapshotID(v)
	})
}

// UpdateSnapshotID sets the "snapshot_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateSnapshotID() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateSnapshotID()
	})
}

// SetItemType sets the "item_type" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetItemType(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetItemType(v)
	})
}

// UpdateItemType sets the "item_type" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateItemType() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateItemType()
	})
}

// SetSourceType sets the "source_type" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetSourceType(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateSourceType() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetSourceID(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) AddSourceID(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateSourceID() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearSourceID() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearSourceID()
	})
}

// SetName sets the "name" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetName(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateName() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetCategory(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateCategory() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearCategory() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearCategory()
	})
}

// SetTier sets the "tier" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetTier(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateTier() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateTier()
	})
}

// ClearTier clears the value of the "tier" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearTier() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearTier()
	})
}

// SetOriginalAmountMinor sets the "original_amount_minor" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetOriginalAmountMinor(v)
	})
}

// AddOriginalAmountMinor adds v to the "original_amount_minor" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) AddOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddOriginalAmountMinor(v)
	})
}

// UpdateOriginalAmountMinor sets the "original_amount_minor" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateOriginalAmountMinor() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateOriginalAmountMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetCurrency(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateCurrency() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateCurrency()
	})
}

// SetRateScaled sets the "rate_scaled" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetRateScaled(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetRateScaled(v)
	})
}

// AddRateScaled adds v to the "rate_scaled" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) AddRateScaled(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddRateScaled(v)
	})
}

// UpdateRateScaled sets the "rate_scaled" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateRateScaled() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateRateScaled()
	})
}

// SetAmountCnyCents sets the "amount_cny_cents" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetAmountCnyCents(v)
	})
}

// AddAmountCnyCents adds v to the "amount_cny_cents" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) AddAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddAmountCnyCents(v)
	})
}

// UpdateAmountCnyCents sets the "amount_cny_cents" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateAmountCnyCents() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateAmountCnyCents()
	})
}

// SetExpiresOn sets the "expires_on" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetExpiresOn(v time.Time) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetExpiresOn(v)
	})
}

// UpdateExpiresOn sets the "expires_on" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateExpiresOn() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateExpiresOn()
	})
}

// ClearExpiresOn clears the value of the "expires_on" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearExpiresOn() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearExpiresOn()
	})
}

// SetReason sets the "reason" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetReason(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateReason() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearReason() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearReason()
	})
}

// SetIncluded sets the "included" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetIncluded(v bool) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetIncluded(v)
	})
}

// UpdateIncluded sets the "included" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateIncluded() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateIncluded()
	})
}

// SetLinkedAPIKeyID sets the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetLinkedAPIKeyID(v)
	})
}

// AddLinkedAPIKeyID adds v to the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) AddLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddLinkedAPIKeyID(v)
	})
}

// UpdateLinkedAPIKeyID sets the "linked_api_key_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateLinkedAPIKeyID()
	})
}

// ClearLinkedAPIKeyID clears the value of the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearLinkedAPIKeyID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetGroupName(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateGroupName() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearGroupName() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearGroupName()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) SetUserEmail(v string) *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertOne) UpdateUserEmail() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *BusinessMonthlySnapshotItemUpsertOne) ClearUserEmail() *BusinessMonthlySnapshotItemUpsertOne {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearUserEmail()
	})
}

// Exec executes the query.
func (u *BusinessMonthlySnapshotItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessMonthlySnapshotItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessMonthlySnapshotItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BusinessMonthlySnapshotItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BusinessMonthlySnapshotItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BusinessMonthlySnapshotItemCreateBulk is the builder for creating many BusinessMonthlySnapshotItem entities in bulk.
type BusinessMonthlySnapshotItemCreateBulk struct {
	config
	err      error
	builders []*BusinessMonthlySnapshotItemCreate
	conflict []sql.ConflictOption
}

// Save creates the BusinessMonthlySnapshotItem entities in the database.
func (_c *BusinessMonthlySnapshotItemCreateBulk) Save(ctx context.Context) ([]*BusinessMonthlySnapshotItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BusinessMonthlySnapshotItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BusinessMonthlySnapshotItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BusinessMonthlySnapshotItemCreateBulk) SaveX(ctx context.Context) []*BusinessMonthlySnapshotItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BusinessMonthlySnapshotItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BusinessMonthlySnapshotItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BusinessMonthlySnapshotItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessMonthlySnapshotItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BusinessMonthlySnapshotItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *BusinessMonthlySnapshotItemUpsertBulk {
	_c.conflict = opts
	return &BusinessMonthlySnapshotItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BusinessMonthlySnapshotItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BusinessMonthlySnapshotItemCreateBulk) OnConflictColumns(columns ...string) *BusinessMonthlySnapshotItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BusinessMonthlySnapshotItemUpsertBulk{
		create: _c,
	}
}

// BusinessMonthlySnapshotItemUpsertBulk is the builder for "upsert"-ing
// a bulk of BusinessMonthlySnapshotItem nodes.
type BusinessMonthlySnapshotItemUpsertBulk struct {
	create *BusinessMonthlySnapshotItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BusinessMonthlySnapshotItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateNewValues() *BusinessMonthlySnapshotItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(businessmonthlysnapshotitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BusinessMonthlySnapshotItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BusinessMonthlySnapshotItemUpsertBulk) Ignore() *BusinessMonthlySnapshotItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessMonthlySnapshotItemUpsertBulk) DoNothing() *BusinessMonthlySnapshotItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessMonthlySnapshotItemCreateBulk.OnConflict
// documentation for more info.
func (u *BusinessMonthlySnapshotItemUpsertBulk) Update(set func(*BusinessMonthlySnapshotItemUpsert)) *BusinessMonthlySnapshotItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessMonthlySnapshotItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetUpdatedAt(v time.Time) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateUpdatedAt() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSnapshotID sets the "snapshot_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetSnapshotID(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetSnapshotID(v)
	})
}

// AddSnapshotID adds v to the "snapshot_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) AddSnapshotID(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddSnapshotID(v)
	})
}

// UpdateSnapshotID sets the "snapshot_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateSnapshotID() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateSnapshotID()
	})
}

// SetItemType sets the "item_type" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetItemType(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetItemType(v)
	})
}

// UpdateItemType sets the "item_type" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateItemType() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateItemType()
	})
}

// SetSourceType sets the "source_type" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetSourceType(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateSourceType() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetSourceID(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) AddSourceID(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateSourceID() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearSourceID() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearSourceID()
	})
}

// SetName sets the "name" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetName(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateName() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetCategory(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateCategory() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearCategory() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearCategory()
	})
}

// SetTier sets the "tier" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetTier(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateTier() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateTier()
	})
}

// ClearTier clears the value of the "tier" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearTier() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearTier()
	})
}

// SetOriginalAmountMinor sets the "original_amount_minor" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetOriginalAmountMinor(v)
	})
}

// AddOriginalAmountMinor adds v to the "original_amount_minor" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) AddOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddOriginalAmountMinor(v)
	})
}

// UpdateOriginalAmountMinor sets the "original_amount_minor" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateOriginalAmountMinor() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateOriginalAmountMinor()
	})
}

// SetCurrency sets the "currency" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetCurrency(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateCurrency() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateCurrency()
	})
}

// SetRateScaled sets the "rate_scaled" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetRateScaled(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetRateScaled(v)
	})
}

// AddRateScaled adds v to the "rate_scaled" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) AddRateScaled(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddRateScaled(v)
	})
}

// UpdateRateScaled sets the "rate_scaled" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateRateScaled() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateRateScaled()
	})
}

// SetAmountCnyCents sets the "amount_cny_cents" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetAmountCnyCents(v)
	})
}

// AddAmountCnyCents adds v to the "amount_cny_cents" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) AddAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddAmountCnyCents(v)
	})
}

// UpdateAmountCnyCents sets the "amount_cny_cents" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateAmountCnyCents() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateAmountCnyCents()
	})
}

// SetExpiresOn sets the "expires_on" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetExpiresOn(v time.Time) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetExpiresOn(v)
	})
}

// UpdateExpiresOn sets the "expires_on" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateExpiresOn() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateExpiresOn()
	})
}

// ClearExpiresOn clears the value of the "expires_on" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearExpiresOn() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearExpiresOn()
	})
}

// SetReason sets the "reason" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetReason(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateReason() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearReason() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearReason()
	})
}

// SetIncluded sets the "included" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetIncluded(v bool) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetIncluded(v)
	})
}

// UpdateIncluded sets the "included" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateIncluded() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateIncluded()
	})
}

// SetLinkedAPIKeyID sets the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetLinkedAPIKeyID(v)
	})
}

// AddLinkedAPIKeyID adds v to the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) AddLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.AddLinkedAPIKeyID(v)
	})
}

// UpdateLinkedAPIKeyID sets the "linked_api_key_id" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateLinkedAPIKeyID()
	})
}

// ClearLinkedAPIKeyID clears the value of the "linked_api_key_id" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearLinkedAPIKeyID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetGroupName(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateGroupName() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearGroupName() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearGroupName()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) SetUserEmail(v string) *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *BusinessMonthlySnapshotItemUpsertBulk) UpdateUserEmail() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ClearUserEmail() *BusinessMonthlySnapshotItemUpsertBulk {
	return u.Update(func(s *BusinessMonthlySnapshotItemUpsert) {
		s.ClearUserEmail()
	})
}

// Exec executes the query.
func (u *BusinessMonthlySnapshotItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BusinessMonthlySnapshotItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessMonthlySnapshotItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessMonthlySnapshotItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
