// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessexchangerate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BusinessExchangeRateDelete is the builder for deleting a BusinessExchangeRate entity.
type BusinessExchangeRateDelete struct {
	config
	hooks    []Hook
	mutation *BusinessExchangeRateMutation
}

// Where appends a list predicates to the BusinessExchangeRateDelete builder.
func (_d *BusinessExchangeRateDelete) Where(ps ...predicate.BusinessExchangeRate) *BusinessExchangeRateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BusinessExchangeRateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessExchangeRateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BusinessExchangeRateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(businessexchangerate.Table, sqlgraph.NewFieldSpec(businessexchangerate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BusinessExchangeRateDeleteOne is the builder for deleting a single BusinessExchangeRate entity.
type BusinessExchangeRateDeleteOne struct {
	_d *BusinessExchangeRateDelete
}

// Where appends a list predicates to the BusinessExchangeRateDelete builder.
func (_d *BusinessExchangeRateDeleteOne) Where(ps ...predicate.BusinessExchangeRate) *BusinessExchangeRateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BusinessExchangeRateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{businessexchangerate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessExchangeRateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
