// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/businesscostitem"
)

// BusinessCostItem is the model entity for the BusinessCostItem schema.
type BusinessCostItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CostClass holds the value of the "cost_class" field.
	CostClass string `json:"cost_class,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// AmountMinor holds the value of the "amount_minor" field.
	AmountMinor int64 `json:"amount_minor,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BillingCycle holds the value of the "billing_cycle" field.
	BillingCycle string `json:"billing_cycle,omitempty"`
	// StartsOn holds the value of the "starts_on" field.
	StartsOn time.Time `json:"starts_on,omitempty"`
	// EndsOn holds the value of the "ends_on" field.
	EndsOn *time.Time `json:"ends_on,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// AccountIdentifier holds the value of the "account_identifier" field.
	AccountIdentifier *string `json:"account_identifier,omitempty"`
	// IsFree holds the value of the "is_free" field.
	IsFree bool `json:"is_free,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        *string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BusinessCostItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case businesscostitem.FieldIsFree, businesscostitem.FieldActive:
			values[i] = new(sql.NullBool)
		case businesscostitem.FieldID, businesscostitem.FieldAmountMinor, businesscostitem.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case businesscostitem.FieldName, businesscostitem.FieldCostClass, businesscostitem.FieldCategory, businesscostitem.FieldCurrency, businesscostitem.FieldBillingCycle, businesscostitem.FieldAccountIdentifier, businesscostitem.FieldNotes:
			values[i] = new(sql.NullString)
		case businesscostitem.FieldCreatedAt, businesscostitem.FieldUpdatedAt, businesscostitem.FieldDeletedAt, businesscostitem.FieldStartsOn, businesscostitem.FieldEndsOn:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BusinessCostItem fields.
func (_m *BusinessCostItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case businesscostitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case businesscostitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case businesscostitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case businesscostitem.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case businesscostitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case businesscostitem.FieldCostClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cost_class", values[i])
			} else if value.Valid {
				_m.CostClass = value.String
			}
		case businesscostitem.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case businesscostitem.FieldAmountMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_minor", values[i])
			} else if value.Valid {
				_m.AmountMinor = value.Int64
			}
		case businesscostitem.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case businesscostitem.FieldBillingCycle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_cycle", values[i])
			} else if value.Valid {
				_m.BillingCycle = value.String
			}
		case businesscostitem.FieldStartsOn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_on", values[i])
			} else if value.Valid {
				_m.StartsOn = value.Time
			}
		case businesscostitem.FieldEndsOn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_on", values[i])
			} else if value.Valid {
				_m.EndsOn = new(time.Time)
				*_m.EndsOn = value.Time
			}
		case businesscostitem.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case businesscostitem.FieldAccountIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_identifier", values[i])
			} else if value.Valid {
				_m.AccountIdentifier = new(string)
				*_m.AccountIdentifier = value.String
			}
		case businesscostitem.FieldIsFree:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_free", values[i])
			} else if value.Valid {
				_m.IsFree = value.Bool
			}
		case businesscostitem.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case businesscostitem.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BusinessCostItem.
// This includes values selected through modifiers, order, etc.
func (_m *BusinessCostItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BusinessCostItem.
// Note that you need to call BusinessCostItem.Unwrap() before calling this method if this BusinessCostItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BusinessCostItem) Update() *BusinessCostItemUpdateOne {
	return NewBusinessCostItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BusinessCostItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BusinessCostItem) Unwrap() *BusinessCostItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BusinessCostItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BusinessCostItem) String() string {
	var builder strings.Builder
	builder.WriteString("BusinessCostItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("cost_class=")
	builder.WriteString(_m.CostClass)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("amount_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountMinor))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("billing_cycle=")
	builder.WriteString(_m.BillingCycle)
	builder.WriteString(", ")
	builder.WriteString("starts_on=")
	builder.WriteString(_m.StartsOn.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndsOn; v != nil {
		builder.WriteString("ends_on=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountIdentifier; v != nil {
		builder.WriteString("account_identifier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_free=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsFree))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BusinessCostItems is a parsable slice of BusinessCostItem.
type BusinessCostItems []*BusinessCostItem
