// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessapikeyconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BusinessAPIKeyConfigUpdate is the builder for updating BusinessAPIKeyConfig entities.
type BusinessAPIKeyConfigUpdate struct {
	config
	hooks    []Hook
	mutation *BusinessAPIKeyConfigMutation
}

// Where appends a list predicates to the BusinessAPIKeyConfigUpdate builder.
func (_u *BusinessAPIKeyConfigUpdate) Where(ps ...predicate.BusinessAPIKeyConfig) *BusinessAPIKeyConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BusinessAPIKeyConfigUpdate) SetUpdatedAt(v time.Time) *BusinessAPIKeyConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *BusinessAPIKeyConfigUpdate) SetAPIKeyID(v int64) *BusinessAPIKeyConfigUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdate) SetNillableAPIKeyID(v *int64) *BusinessAPIKeyConfigUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *BusinessAPIKeyConfigUpdate) AddAPIKeyID(v int64) *BusinessAPIKeyConfigUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetRevenueExcluded sets the "revenue_excluded" field.
func (_u *BusinessAPIKeyConfigUpdate) SetRevenueExcluded(v bool) *BusinessAPIKeyConfigUpdate {
	_u.mutation.SetRevenueExcluded(v)
	return _u
}

// SetNillableRevenueExcluded sets the "revenue_excluded" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdate) SetNillableRevenueExcluded(v *bool) *BusinessAPIKeyConfigUpdate {
	if v != nil {
		_u.SetRevenueExcluded(*v)
	}
	return _u
}

// SetOverrideAmountCents sets the "override_amount_cents" field.
func (_u *BusinessAPIKeyConfigUpdate) SetOverrideAmountCents(v int64) *BusinessAPIKeyConfigUpdate {
	_u.mutation.ResetOverrideAmountCents()
	_u.mutation.SetOverrideAmountCents(v)
	return _u
}

// SetNillableOverrideAmountCents sets the "override_amount_cents" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdate) SetNillableOverrideAmountCents(v *int64) *BusinessAPIKeyConfigUpdate {
	if v != nil {
		_u.SetOverrideAmountCents(*v)
	}
	return _u
}

// AddOverrideAmountCents adds value to the "override_amount_cents" field.
func (_u *BusinessAPIKeyConfigUpdate) AddOverrideAmountCents(v int64) *BusinessAPIKeyConfigUpdate {
	_u.mutation.AddOverrideAmountCents(v)
	return _u
}

// ClearOverrideAmountCents clears the value of the "override_amount_cents" field.
func (_u *BusinessAPIKeyConfigUpdate) ClearOverrideAmountCents() *BusinessAPIKeyConfigUpdate {
	_u.mutation.ClearOverrideAmountCents()
	return _u
}

// SetPrivateSubscriptionID sets the "private_subscription_id" field.
func (_u *BusinessAPIKeyConfigUpdate) SetPrivateSubscriptionID(v int64) *BusinessAPIKeyConfigUpdate {
	_u.mutation.ResetPrivateSubscriptionID()
	_u.mutation.SetPrivateSubscriptionID(v)
	return _u
}

// SetNillablePrivateSubscriptionID sets the "private_subscription_id" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdate) SetNillablePrivateSubscriptionID(v *int64) *BusinessAPIKeyConfigUpdate {
	if v != nil {
		_u.SetPrivateSubscriptionID(*v)
	}
	return _u
}

// AddPrivateSubscriptionID adds value to the "private_subscription_id" field.
func (_u *BusinessAPIKeyConfigUpdate) AddPrivateSubscriptionID(v int64) *BusinessAPIKeyConfigUpdate {
	_u.mutation.AddPrivateSubscriptionID(v)
	return _u
}

// ClearPrivateSubscriptionID clears the value of the "private_subscription_id" field.
func (_u *BusinessAPIKeyConfigUpdate) ClearPrivateSubscriptionID() *BusinessAPIKeyConfigUpdate {
	_u.mutation.ClearPrivateSubscriptionID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *BusinessAPIKeyConfigUpdate) SetReason(v string) *BusinessAPIKeyConfigUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdate) SetNillableReason(v *string) *BusinessAPIKeyConfigUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *BusinessAPIKeyConfigUpdate) ClearReason() *BusinessAPIKeyConfigUpdate {
	_u.mutation.ClearReason()
	return _u
}

// Mutation returns the BusinessAPIKeyConfigMutation object of the builder.
func (_u *BusinessAPIKeyConfigUpdate) Mutation() *BusinessAPIKeyConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BusinessAPIKeyConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessAPIKeyConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BusinessAPIKeyConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessAPIKeyConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BusinessAPIKeyConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := businessapikeyconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessAPIKeyConfigUpdate) check() error {
	if v, ok := _u.mutation.OverrideAmountCents(); ok {
		if err := businessapikeyconfig.OverrideAmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "override_amount_cents", err: fmt.Errorf(`ent: validator failed for field "BusinessAPIKeyConfig.override_amount_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *BusinessAPIKeyConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businessapikeyconfig.Table, businessapikeyconfig.Columns, sqlgraph.NewFieldSpec(businessapikeyconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(businessapikeyconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(businessapikeyconfig.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(businessapikeyconfig.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RevenueExcluded(); ok {
		_spec.SetField(businessapikeyconfig.FieldRevenueExcluded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OverrideAmountCents(); ok {
		_spec.SetField(businessapikeyconfig.FieldOverrideAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOverrideAmountCents(); ok {
		_spec.AddField(businessapikeyconfig.FieldOverrideAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.OverrideAmountCentsCleared() {
		_spec.ClearField(businessapikeyconfig.FieldOverrideAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.PrivateSubscriptionID(); ok {
		_spec.SetField(businessapikeyconfig.FieldPrivateSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrivateSubscriptionID(); ok {
		_spec.AddField(businessapikeyconfig.FieldPrivateSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.PrivateSubscriptionIDCleared() {
		_spec.ClearField(businessapikeyconfig.FieldPrivateSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(businessapikeyconfig.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(businessapikeyconfig.FieldReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businessapikeyconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BusinessAPIKeyConfigUpdateOne is the builder for updating a single BusinessAPIKeyConfig entity.
type BusinessAPIKeyConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BusinessAPIKeyConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BusinessAPIKeyConfigUpdateOne) SetUpdatedAt(v time.Time) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *BusinessAPIKeyConfigUpdateOne) SetAPIKeyID(v int64) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdateOne) SetNillableAPIKeyID(v *int64) *BusinessAPIKeyConfigUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *BusinessAPIKeyConfigUpdateOne) AddAPIKeyID(v int64) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetRevenueExcluded sets the "revenue_excluded" field.
func (_u *BusinessAPIKeyConfigUpdateOne) SetRevenueExcluded(v bool) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.SetRevenueExcluded(v)
	return _u
}

// SetNillableRevenueExcluded sets the "revenue_excluded" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdateOne) SetNillableRevenueExcluded(v *bool) *BusinessAPIKeyConfigUpdateOne {
	if v != nil {
		_u.SetRevenueExcluded(*v)
	}
	return _u
}

// SetOverrideAmountCents sets the "override_amount_cents" field.
func (_u *BusinessAPIKeyConfigUpdateOne) SetOverrideAmountCents(v int64) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.ResetOverrideAmountCents()
	_u.mutation.SetOverrideAmountCents(v)
	return _u
}

// SetNillableOverrideAmountCents sets the "override_amount_cents" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdateOne) SetNillableOverrideAmountCents(v *int64) *BusinessAPIKeyConfigUpdateOne {
	if v != nil {
		_u.SetOverrideAmountCents(*v)
	}
	return _u
}

// AddOverrideAmountCents adds value to the "override_amount_cents" field.
func (_u *BusinessAPIKeyConfigUpdateOne) AddOverrideAmountCents(v int64) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.AddOverrideAmountCents(v)
	return _u
}

// ClearOverrideAmountCents clears the value of the "override_amount_cents" field.
func (_u *BusinessAPIKeyConfigUpdateOne) ClearOverrideAmountCents() *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.ClearOverrideAmountCents()
	return _u
}

// SetPrivateSubscriptionID sets the "private_subscription_id" field.
func (_u *BusinessAPIKeyConfigUpdateOne) SetPrivateSubscriptionID(v int64) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.ResetPrivateSubscriptionID()
	_u.mutation.SetPrivateSubscriptionID(v)
	return _u
}

// SetNillablePrivateSubscriptionID sets the "private_subscription_id" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdateOne) SetNillablePrivateSubscriptionID(v *int64) *BusinessAPIKeyConfigUpdateOne {
	if v != nil {
		_u.SetPrivateSubscriptionID(*v)
	}
	return _u
}

// AddPrivateSubscriptionID adds value to the "private_subscription_id" field.
func (_u *BusinessAPIKeyConfigUpdateOne) AddPrivateSubscriptionID(v int64) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.AddPrivateSubscriptionID(v)
	return _u
}

// ClearPrivateSubscriptionID clears the value of the "private_subscription_id" field.
func (_u *BusinessAPIKeyConfigUpdateOne) ClearPrivateSubscriptionID() *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.ClearPrivateSubscriptionID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *BusinessAPIKeyConfigUpdateOne) SetReason(v string) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BusinessAPIKeyConfigUpdateOne) SetNillableReason(v *string) *BusinessAPIKeyConfigUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *BusinessAPIKeyConfigUpdateOne) ClearReason() *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// Mutation returns the BusinessAPIKeyConfigMutation object of the builder.
func (_u *BusinessAPIKeyConfigUpdateOne) Mutation() *BusinessAPIKeyConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the BusinessAPIKeyConfigUpdate builder.
func (_u *BusinessAPIKeyConfigUpdateOne) Where(ps ...predicate.BusinessAPIKeyConfig) *BusinessAPIKeyConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BusinessAPIKeyConfigUpdateOne) Select(field string, fields ...string) *BusinessAPIKeyConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BusinessAPIKeyConfig entity.
func (_u *BusinessAPIKeyConfigUpdateOne) Save(ctx context.Context) (*BusinessAPIKeyConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessAPIKeyConfigUpdateOne) SaveX(ctx context.Context) *BusinessAPIKeyConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BusinessAPIKeyConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessAPIKeyConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BusinessAPIKeyConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := businessapikeyconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessAPIKeyConfigUpdateOne) check() error {
	if v, ok := _u.mutation.OverrideAmountCents(); ok {
		if err := businessapikeyconfig.OverrideAmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "override_amount_cents", err: fmt.Errorf(`ent: validator failed for field "BusinessAPIKeyConfig.override_amount_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *BusinessAPIKeyConfigUpdateOne) sqlSave(ctx context.Context) (_node *BusinessAPIKeyConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businessapikeyconfig.Table, businessapikeyconfig.Columns, sqlgraph.NewFieldSpec(businessapikeyconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BusinessAPIKeyConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businessapikeyconfig.FieldID)
		for _, f := range fields {
			if !businessapikeyconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != businessapikeyconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(businessapikeyconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(businessapikeyconfig.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(businessapikeyconfig.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RevenueExcluded(); ok {
		_spec.SetField(businessapikeyconfig.FieldRevenueExcluded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OverrideAmountCents(); ok {
		_spec.SetField(businessapikeyconfig.FieldOverrideAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOverrideAmountCents(); ok {
		_spec.AddField(businessapikeyconfig.FieldOverrideAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.OverrideAmountCentsCleared() {
		_spec.ClearField(businessapikeyconfig.FieldOverrideAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.PrivateSubscriptionID(); ok {
		_spec.SetField(businessapikeyconfig.FieldPrivateSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrivateSubscriptionID(); ok {
		_spec.AddField(businessapikeyconfig.FieldPrivateSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.PrivateSubscriptionIDCleared() {
		_spec.ClearField(businessapikeyconfig.FieldPrivateSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(businessapikeyconfig.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(businessapikeyconfig.FieldReason, field.TypeString)
	}
	_node = &BusinessAPIKeyConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businessapikeyconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
