// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businesspricingrule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BusinessPricingRuleUpdate is the builder for updating BusinessPricingRule entities.
type BusinessPricingRuleUpdate struct {
	config
	hooks    []Hook
	mutation *BusinessPricingRuleMutation
}

// Where appends a list predicates to the BusinessPricingRuleUpdate builder.
func (_u *BusinessPricingRuleUpdate) Where(ps ...predicate.BusinessPricingRule) *BusinessPricingRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BusinessPricingRuleUpdate) SetUpdatedAt(v time.Time) *BusinessPricingRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BusinessPricingRuleUpdate) SetGroupID(v int64) *BusinessPricingRuleUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdate) SetNillableGroupID(v *int64) *BusinessPricingRuleUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *BusinessPricingRuleUpdate) AddGroupID(v int64) *BusinessPricingRuleUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetTier sets the "tier" field.
func (_u *BusinessPricingRuleUpdate) SetTier(v string) *BusinessPricingRuleUpdate {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdate) SetNillableTier(v *string) *BusinessPricingRuleUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetMonthlyPriceCents sets the "monthly_price_cents" field.
func (_u *BusinessPricingRuleUpdate) SetMonthlyPriceCents(v int64) *BusinessPricingRuleUpdate {
	_u.mutation.ResetMonthlyPriceCents()
	_u.mutation.SetMonthlyPriceCents(v)
	return _u
}

// SetNillableMonthlyPriceCents sets the "monthly_price_cents" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdate) SetNillableMonthlyPriceCents(v *int64) *BusinessPricingRuleUpdate {
	if v != nil {
		_u.SetMonthlyPriceCents(*v)
	}
	return _u
}

// AddMonthlyPriceCents adds value to the "monthly_price_cents" field.
func (_u *BusinessPricingRuleUpdate) AddMonthlyPriceCents(v int64) *BusinessPricingRuleUpdate {
	_u.mutation.AddMonthlyPriceCents(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *BusinessPricingRuleUpdate) SetActive(v bool) *BusinessPricingRuleUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdate) SetNillableActive(v *bool) *BusinessPricingRuleUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BusinessPricingRuleUpdate) SetNotes(v string) *BusinessPricingRuleUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdate) SetNillableNotes(v *string) *BusinessPricingRuleUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BusinessPricingRuleUpdate) ClearNotes() *BusinessPricingRuleUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the BusinessPricingRuleMutation object of the builder.
func (_u *BusinessPricingRuleUpdate) Mutation() *BusinessPricingRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BusinessPricingRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessPricingRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BusinessPricingRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessPricingRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BusinessPricingRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := businesspricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessPricingRuleUpdate) check() error {
	if v, ok := _u.mutation.Tier(); ok {
		if err := businesspricingrule.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BusinessPricingRule.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MonthlyPriceCents(); ok {
		if err := businesspricingrule.MonthlyPriceCentsValidator(v); err != nil {
			return &ValidationError{Name: "monthly_price_cents", err: fmt.Errorf(`ent: validator failed for field "BusinessPricingRule.monthly_price_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *BusinessPricingRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businesspricingrule.Table, businesspricingrule.Columns, sqlgraph.NewFieldSpec(businesspricingrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(businesspricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(businesspricingrule.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(businesspricingrule.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(businesspricingrule.FieldTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonthlyPriceCents(); ok {
		_spec.SetField(businesspricingrule.FieldMonthlyPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyPriceCents(); ok {
		_spec.AddField(businesspricingrule.FieldMonthlyPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(businesspricingrule.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(businesspricingrule.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(businesspricingrule.FieldNotes, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businesspricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BusinessPricingRuleUpdateOne is the builder for updating a single BusinessPricingRule entity.
type BusinessPricingRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BusinessPricingRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BusinessPricingRuleUpdateOne) SetUpdatedAt(v time.Time) *BusinessPricingRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BusinessPricingRuleUpdateOne) SetGroupID(v int64) *BusinessPricingRuleUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdateOne) SetNillableGroupID(v *int64) *BusinessPricingRuleUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *BusinessPricingRuleUpdateOne) AddGroupID(v int64) *BusinessPricingRuleUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetTier sets the "tier" field.
func (_u *BusinessPricingRuleUpdateOne) SetTier(v string) *BusinessPricingRuleUpdateOne {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdateOne) SetNillableTier(v *string) *BusinessPricingRuleUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetMonthlyPriceCents sets the "monthly_price_cents" field.
func (_u *BusinessPricingRuleUpdateOne) SetMonthlyPriceCents(v int64) *BusinessPricingRuleUpdateOne {
	_u.mutation.ResetMonthlyPriceCents()
	_u.mutation.SetMonthlyPriceCents(v)
	return _u
}

// SetNillableMonthlyPriceCents sets the "monthly_price_cents" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdateOne) SetNillableMonthlyPriceCents(v *int64) *BusinessPricingRuleUpdateOne {
	if v != nil {
		_u.SetMonthlyPriceCents(*v)
	}
	return _u
}

// AddMonthlyPriceCents adds value to the "monthly_price_cents" field.
func (_u *BusinessPricingRuleUpdateOne) AddMonthlyPriceCents(v int64) *BusinessPricingRuleUpdateOne {
	_u.mutation.AddMonthlyPriceCents(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *BusinessPricingRuleUpdateOne) SetActive(v bool) *BusinessPricingRuleUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdateOne) SetNillableActive(v *bool) *BusinessPricingRuleUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BusinessPricingRuleUpdateOne) SetNotes(v string) *BusinessPricingRuleUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BusinessPricingRuleUpdateOne) SetNillableNotes(v *string) *BusinessPricingRuleUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BusinessPricingRuleUpdateOne) ClearNotes() *BusinessPricingRuleUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the BusinessPricingRuleMutation object of the builder.
func (_u *BusinessPricingRuleUpdateOne) Mutation() *BusinessPricingRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the BusinessPricingRuleUpdate builder.
func (_u *BusinessPricingRuleUpdateOne) Where(ps ...predicate.BusinessPricingRule) *BusinessPricingRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BusinessPricingRuleUpdateOne) Select(field string, fields ...string) *BusinessPricingRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BusinessPricingRule entity.
func (_u *BusinessPricingRuleUpdateOne) Save(ctx context.Context) (*BusinessPricingRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessPricingRuleUpdateOne) SaveX(ctx context.Context) *BusinessPricingRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BusinessPricingRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessPricingRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BusinessPricingRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := businesspricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessPricingRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Tier(); ok {
		if err := businesspricingrule.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BusinessPricingRule.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MonthlyPriceCents(); ok {
		if err := businesspricingrule.MonthlyPriceCentsValidator(v); err != nil {
			return &ValidationError{Name: "monthly_price_cents", err: fmt.Errorf(`ent: validator failed for field "BusinessPricingRule.monthly_price_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *BusinessPricingRuleUpdateOne) sqlSave(ctx context.Context) (_node *BusinessPricingRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businesspricingrule.Table, businesspricingrule.Columns, sqlgraph.NewFieldSpec(businesspricingrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BusinessPricingRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businesspricingrule.FieldID)
		for _, f := range fields {
			if !businesspricingrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != businesspricingrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(businesspricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(businesspricingrule.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(businesspricingrule.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(businesspricingrule.FieldTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonthlyPriceCents(); ok {
		_spec.SetField(businesspricingrule.FieldMonthlyPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyPriceCents(); ok {
		_spec.AddField(businesspricingrule.FieldMonthlyPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(businesspricingrule.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(businesspricingrule.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(businesspricingrule.FieldNotes, field.TypeString)
	}
	_node = &BusinessPricingRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businesspricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
