// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessmonthlysnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BusinessMonthlySnapshotDelete is the builder for deleting a BusinessMonthlySnapshot entity.
type BusinessMonthlySnapshotDelete struct {
	config
	hooks    []Hook
	mutation *BusinessMonthlySnapshotMutation
}

// Where appends a list predicates to the BusinessMonthlySnapshotDelete builder.
func (_d *BusinessMonthlySnapshotDelete) Where(ps ...predicate.BusinessMonthlySnapshot) *BusinessMonthlySnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BusinessMonthlySnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessMonthlySnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BusinessMonthlySnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(businessmonthlysnapshot.Table, sqlgraph.NewFieldSpec(businessmonthlysnapshot.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BusinessMonthlySnapshotDeleteOne is the builder for deleting a single BusinessMonthlySnapshot entity.
type BusinessMonthlySnapshotDeleteOne struct {
	_d *BusinessMonthlySnapshotDelete
}

// Where appends a list predicates to the BusinessMonthlySnapshotDelete builder.
func (_d *BusinessMonthlySnapshotDeleteOne) Where(ps ...predicate.BusinessMonthlySnapshot) *BusinessMonthlySnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BusinessMonthlySnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{businessmonthlysnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BusinessMonthlySnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
