// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/businessmonthlysnapshotitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BusinessMonthlySnapshotItemUpdate is the builder for updating BusinessMonthlySnapshotItem entities.
type BusinessMonthlySnapshotItemUpdate struct {
	config
	hooks    []Hook
	mutation *BusinessMonthlySnapshotItemMutation
}

// Where appends a list predicates to the BusinessMonthlySnapshotItemUpdate builder.
func (_u *BusinessMonthlySnapshotItemUpdate) Where(ps ...predicate.BusinessMonthlySnapshotItem) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetUpdatedAt(v time.Time) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSnapshotID sets the "snapshot_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetSnapshotID(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ResetSnapshotID()
	_u.mutation.SetSnapshotID(v)
	return _u
}

// SetNillableSnapshotID sets the "snapshot_id" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableSnapshotID(v *int64) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetSnapshotID(*v)
	}
	return _u
}

// AddSnapshotID adds value to the "snapshot_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) AddSnapshotID(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.AddSnapshotID(v)
	return _u
}

// SetItemType sets the "item_type" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetItemType(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetItemType(v)
	return _u
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableItemType(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetItemType(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetSourceType(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableSourceType(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetSourceID(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableSourceID(v *int64) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) AddSourceID(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearSourceID() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetName sets the "name" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetName(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableName(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetCategory(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableCategory(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearCategory() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetTier sets the "tier" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetTier(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableTier(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// ClearTier clears the value of the "tier" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearTier() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearTier()
	return _u
}

// SetOriginalAmountMinor sets the "original_amount_minor" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ResetOriginalAmountMinor()
	_u.mutation.SetOriginalAmountMinor(v)
	return _u
}

// SetNillableOriginalAmountMinor sets the "original_amount_minor" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableOriginalAmountMinor(v *int64) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetOriginalAmountMinor(*v)
	}
	return _u
}

// AddOriginalAmountMinor adds value to the "original_amount_minor" field.
func (_u *BusinessMonthlySnapshotItemUpdate) AddOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.AddOriginalAmountMinor(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetCurrency(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableCurrency(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRateScaled sets the "rate_scaled" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetRateScaled(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ResetRateScaled()
	_u.mutation.SetRateScaled(v)
	return _u
}

// SetNillableRateScaled sets the "rate_scaled" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableRateScaled(v *int64) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetRateScaled(*v)
	}
	return _u
}

// AddRateScaled adds value to the "rate_scaled" field.
func (_u *BusinessMonthlySnapshotItemUpdate) AddRateScaled(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.AddRateScaled(v)
	return _u
}

// SetAmountCnyCents sets the "amount_cny_cents" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ResetAmountCnyCents()
	_u.mutation.SetAmountCnyCents(v)
	return _u
}

// SetNillableAmountCnyCents sets the "amount_cny_cents" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableAmountCnyCents(v *int64) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetAmountCnyCents(*v)
	}
	return _u
}

// AddAmountCnyCents adds value to the "amount_cny_cents" field.
func (_u *BusinessMonthlySnapshotItemUpdate) AddAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.AddAmountCnyCents(v)
	return _u
}

// SetExpiresOn sets the "expires_on" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetExpiresOn(v time.Time) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetExpiresOn(v)
	return _u
}

// SetNillableExpiresOn sets the "expires_on" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableExpiresOn(v *time.Time) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetExpiresOn(*v)
	}
	return _u
}

// ClearExpiresOn clears the value of the "expires_on" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearExpiresOn() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearExpiresOn()
	return _u
}

// SetReason sets the "reason" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetReason(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableReason(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearReason() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetIncluded sets the "included" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetIncluded(v bool) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetIncluded(v)
	return _u
}

// SetNillableIncluded sets the "included" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableIncluded(v *bool) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetIncluded(*v)
	}
	return _u
}

// SetLinkedAPIKeyID sets the "linked_api_key_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ResetLinkedAPIKeyID()
	_u.mutation.SetLinkedAPIKeyID(v)
	return _u
}

// SetNillableLinkedAPIKeyID sets the "linked_api_key_id" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableLinkedAPIKeyID(v *int64) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetLinkedAPIKeyID(*v)
	}
	return _u
}

// AddLinkedAPIKeyID adds value to the "linked_api_key_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) AddLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.AddLinkedAPIKeyID(v)
	return _u
}

// ClearLinkedAPIKeyID clears the value of the "linked_api_key_id" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearLinkedAPIKeyID()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetGroupName(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableGroupName(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearGroupName() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearGroupName()
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *BusinessMonthlySnapshotItemUpdate) SetUserEmail(v string) *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdate) SetNillableUserEmail(v *string) *BusinessMonthlySnapshotItemUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// ClearUserEmail clears the value of the "user_email" field.
func (_u *BusinessMonthlySnapshotItemUpdate) ClearUserEmail() *BusinessMonthlySnapshotItemUpdate {
	_u.mutation.ClearUserEmail()
	return _u
}

// Mutation returns the BusinessMonthlySnapshotItemMutation object of the builder.
func (_u *BusinessMonthlySnapshotItemUpdate) Mutation() *BusinessMonthlySnapshotItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BusinessMonthlySnapshotItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessMonthlySnapshotItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BusinessMonthlySnapshotItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessMonthlySnapshotItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BusinessMonthlySnapshotItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := businessmonthlysnapshotitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessMonthlySnapshotItemUpdate) check() error {
	if v, ok := _u.mutation.ItemType(); ok {
		if err := businessmonthlysnapshotitem.ItemTypeValidator(v); err != nil {
			return &ValidationError{Name: "item_type", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.item_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := businessmonthlysnapshotitem.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := businessmonthlysnapshotitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := businessmonthlysnapshotitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tier(); ok {
		if err := businessmonthlysnapshotitem.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := businessmonthlysnapshotitem.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateScaled(); ok {
		if err := businessmonthlysnapshotitem.RateScaledValidator(v); err != nil {
			return &ValidationError{Name: "rate_scaled", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.rate_scaled": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := businessmonthlysnapshotitem.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := businessmonthlysnapshotitem.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.user_email": %w`, err)}
		}
	}
	return nil
}

func (_u *BusinessMonthlySnapshotItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businessmonthlysnapshotitem.Table, businessmonthlysnapshotitem.Columns, sqlgraph.NewFieldSpec(businessmonthlysnapshotitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SnapshotID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSnapshotID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotID(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldSnapshotID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ItemType(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldItemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldTier, field.TypeString, value)
	}
	if _u.mutation.TierCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldTier, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalAmountMinor(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldOriginalAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOriginalAmountMinor(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldOriginalAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateScaled(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldRateScaled, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRateScaled(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldRateScaled, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AmountCnyCents(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldAmountCnyCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCnyCents(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldAmountCnyCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresOn(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldExpiresOn, field.TypeTime, value)
	}
	if _u.mutation.ExpiresOnCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldExpiresOn, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Included(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldIncluded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LinkedAPIKeyID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLinkedAPIKeyID(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.LinkedAPIKeyIDCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldUserEmail, field.TypeString, value)
	}
	if _u.mutation.UserEmailCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldUserEmail, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businessmonthlysnapshotitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BusinessMonthlySnapshotItemUpdateOne is the builder for updating a single BusinessMonthlySnapshotItem entity.
type BusinessMonthlySnapshotItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BusinessMonthlySnapshotItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetUpdatedAt(v time.Time) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSnapshotID sets the "snapshot_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetSnapshotID(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ResetSnapshotID()
	_u.mutation.SetSnapshotID(v)
	return _u
}

// SetNillableSnapshotID sets the "snapshot_id" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableSnapshotID(v *int64) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetSnapshotID(*v)
	}
	return _u
}

// AddSnapshotID adds value to the "snapshot_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) AddSnapshotID(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.AddSnapshotID(v)
	return _u
}

// SetItemType sets the "item_type" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetItemType(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetItemType(v)
	return _u
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableItemType(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetItemType(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetSourceType(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableSourceType(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetSourceID(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableSourceID(v *int64) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) AddSourceID(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearSourceID() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetName sets the "name" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetName(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableName(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetCategory(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableCategory(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearCategory() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetTier sets the "tier" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetTier(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableTier(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// ClearTier clears the value of the "tier" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearTier() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearTier()
	return _u
}

// SetOriginalAmountMinor sets the "original_amount_minor" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ResetOriginalAmountMinor()
	_u.mutation.SetOriginalAmountMinor(v)
	return _u
}

// SetNillableOriginalAmountMinor sets the "original_amount_minor" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableOriginalAmountMinor(v *int64) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetOriginalAmountMinor(*v)
	}
	return _u
}

// AddOriginalAmountMinor adds value to the "original_amount_minor" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) AddOriginalAmountMinor(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.AddOriginalAmountMinor(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetCurrency(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableCurrency(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRateScaled sets the "rate_scaled" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetRateScaled(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ResetRateScaled()
	_u.mutation.SetRateScaled(v)
	return _u
}

// SetNillableRateScaled sets the "rate_scaled" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableRateScaled(v *int64) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetRateScaled(*v)
	}
	return _u
}

// AddRateScaled adds value to the "rate_scaled" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) AddRateScaled(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.AddRateScaled(v)
	return _u
}

// SetAmountCnyCents sets the "amount_cny_cents" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ResetAmountCnyCents()
	_u.mutation.SetAmountCnyCents(v)
	return _u
}

// SetNillableAmountCnyCents sets the "amount_cny_cents" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableAmountCnyCents(v *int64) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetAmountCnyCents(*v)
	}
	return _u
}

// AddAmountCnyCents adds value to the "amount_cny_cents" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) AddAmountCnyCents(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.AddAmountCnyCents(v)
	return _u
}

// SetExpiresOn sets the "expires_on" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetExpiresOn(v time.Time) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetExpiresOn(v)
	return _u
}

// SetNillableExpiresOn sets the "expires_on" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableExpiresOn(v *time.Time) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetExpiresOn(*v)
	}
	return _u
}

// ClearExpiresOn clears the value of the "expires_on" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearExpiresOn() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearExpiresOn()
	return _u
}

// SetReason sets the "reason" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetReason(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableReason(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearReason() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetIncluded sets the "included" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetIncluded(v bool) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetIncluded(v)
	return _u
}

// SetNillableIncluded sets the "included" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableIncluded(v *bool) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetIncluded(*v)
	}
	return _u
}

// SetLinkedAPIKeyID sets the "linked_api_key_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ResetLinkedAPIKeyID()
	_u.mutation.SetLinkedAPIKeyID(v)
	return _u
}

// SetNillableLinkedAPIKeyID sets the "linked_api_key_id" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableLinkedAPIKeyID(v *int64) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetLinkedAPIKeyID(*v)
	}
	return _u
}

// AddLinkedAPIKeyID adds value to the "linked_api_key_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) AddLinkedAPIKeyID(v int64) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.AddLinkedAPIKeyID(v)
	return _u
}

// ClearLinkedAPIKeyID clears the value of the "linked_api_key_id" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearLinkedAPIKeyID() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearLinkedAPIKeyID()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetGroupName(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableGroupName(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearGroupName() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearGroupName()
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetUserEmail(v string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SetNillableUserEmail(v *string) *BusinessMonthlySnapshotItemUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// ClearUserEmail clears the value of the "user_email" field.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ClearUserEmail() *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.ClearUserEmail()
	return _u
}

// Mutation returns the BusinessMonthlySnapshotItemMutation object of the builder.
func (_u *BusinessMonthlySnapshotItemUpdateOne) Mutation() *BusinessMonthlySnapshotItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the BusinessMonthlySnapshotItemUpdate builder.
func (_u *BusinessMonthlySnapshotItemUpdateOne) Where(ps ...predicate.BusinessMonthlySnapshotItem) *BusinessMonthlySnapshotItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BusinessMonthlySnapshotItemUpdateOne) Select(field string, fields ...string) *BusinessMonthlySnapshotItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BusinessMonthlySnapshotItem entity.
func (_u *BusinessMonthlySnapshotItemUpdateOne) Save(ctx context.Context) (*BusinessMonthlySnapshotItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BusinessMonthlySnapshotItemUpdateOne) SaveX(ctx context.Context) *BusinessMonthlySnapshotItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BusinessMonthlySnapshotItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BusinessMonthlySnapshotItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BusinessMonthlySnapshotItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := businessmonthlysnapshotitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BusinessMonthlySnapshotItemUpdateOne) check() error {
	if v, ok := _u.mutation.ItemType(); ok {
		if err := businessmonthlysnapshotitem.ItemTypeValidator(v); err != nil {
			return &ValidationError{Name: "item_type", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.item_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := businessmonthlysnapshotitem.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := businessmonthlysnapshotitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := businessmonthlysnapshotitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tier(); ok {
		if err := businessmonthlysnapshotitem.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := businessmonthlysnapshotitem.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateScaled(); ok {
		if err := businessmonthlysnapshotitem.RateScaledValidator(v); err != nil {
			return &ValidationError{Name: "rate_scaled", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.rate_scaled": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := businessmonthlysnapshotitem.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := businessmonthlysnapshotitem.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "BusinessMonthlySnapshotItem.user_email": %w`, err)}
		}
	}
	return nil
}

func (_u *BusinessMonthlySnapshotItemUpdateOne) sqlSave(ctx context.Context) (_node *BusinessMonthlySnapshotItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(businessmonthlysnapshotitem.Table, businessmonthlysnapshotitem.Columns, sqlgraph.NewFieldSpec(businessmonthlysnapshotitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BusinessMonthlySnapshotItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businessmonthlysnapshotitem.FieldID)
		for _, f := range fields {
			if !businessmonthlysnapshotitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != businessmonthlysnapshotitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SnapshotID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSnapshotID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotID(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldSnapshotID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ItemType(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldItemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldTier, field.TypeString, value)
	}
	if _u.mutation.TierCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldTier, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalAmountMinor(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldOriginalAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOriginalAmountMinor(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldOriginalAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateScaled(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldRateScaled, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRateScaled(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldRateScaled, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AmountCnyCents(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldAmountCnyCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCnyCents(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldAmountCnyCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresOn(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldExpiresOn, field.TypeTime, value)
	}
	if _u.mutation.ExpiresOnCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldExpiresOn, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Included(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldIncluded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LinkedAPIKeyID(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLinkedAPIKeyID(); ok {
		_spec.AddField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.LinkedAPIKeyIDCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldLinkedAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(businessmonthlysnapshotitem.FieldUserEmail, field.TypeString, value)
	}
	if _u.mutation.UserEmailCleared() {
		_spec.ClearField(businessmonthlysnapshotitem.FieldUserEmail, field.TypeString)
	}
	_node = &BusinessMonthlySnapshotItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{businessmonthlysnapshotitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
