// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/privatecustomersubscription"
)

// PrivateCustomerSubscriptionUpdate is the builder for updating PrivateCustomerSubscription entities.
type PrivateCustomerSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *PrivateCustomerSubscriptionMutation
}

// Where appends a list predicates to the PrivateCustomerSubscriptionUpdate builder.
func (_u *PrivateCustomerSubscriptionUpdate) Where(ps ...predicate.PrivateCustomerSubscription) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetUpdatedAt(v time.Time) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetDeletedAt(v time.Time) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableDeletedAt(v *time.Time) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PrivateCustomerSubscriptionUpdate) ClearDeletedAt() *PrivateCustomerSubscriptionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetName(v string) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableName(v *string) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubscriptionType sets the "subscription_type" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetSubscriptionType(v string) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetSubscriptionType(v)
	return _u
}

// SetNillableSubscriptionType sets the "subscription_type" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableSubscriptionType(v *string) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetSubscriptionType(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetAmountCents(v int64) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableAmountCents(v *int64) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PrivateCustomerSubscriptionUpdate) AddAmountCents(v int64) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetExpiresOn sets the "expires_on" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetExpiresOn(v time.Time) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetExpiresOn(v)
	return _u
}

// SetNillableExpiresOn sets the "expires_on" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableExpiresOn(v *time.Time) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetExpiresOn(*v)
	}
	return _u
}

// SetReminderSentForExpiry sets the "reminder_sent_for_expiry" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetReminderSentForExpiry(v time.Time) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetReminderSentForExpiry(v)
	return _u
}

// SetNillableReminderSentForExpiry sets the "reminder_sent_for_expiry" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableReminderSentForExpiry(v *time.Time) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetReminderSentForExpiry(*v)
	}
	return _u
}

// ClearReminderSentForExpiry clears the value of the "reminder_sent_for_expiry" field.
func (_u *PrivateCustomerSubscriptionUpdate) ClearReminderSentForExpiry() *PrivateCustomerSubscriptionUpdate {
	_u.mutation.ClearReminderSentForExpiry()
	return _u
}

// SetReminderSentAt sets the "reminder_sent_at" field.
func (_u *PrivateCustomerSubscriptionUpdate) SetReminderSentAt(v time.Time) *PrivateCustomerSubscriptionUpdate {
	_u.mutation.SetReminderSentAt(v)
	return _u
}

// SetNillableReminderSentAt sets the "reminder_sent_at" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdate) SetNillableReminderSentAt(v *time.Time) *PrivateCustomerSubscriptionUpdate {
	if v != nil {
		_u.SetReminderSentAt(*v)
	}
	return _u
}

// ClearReminderSentAt clears the value of the "reminder_sent_at" field.
func (_u *PrivateCustomerSubscriptionUpdate) ClearReminderSentAt() *PrivateCustomerSubscriptionUpdate {
	_u.mutation.ClearReminderSentAt()
	return _u
}

// Mutation returns the PrivateCustomerSubscriptionMutation object of the builder.
func (_u *PrivateCustomerSubscriptionUpdate) Mutation() *PrivateCustomerSubscriptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PrivateCustomerSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrivateCustomerSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PrivateCustomerSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrivateCustomerSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrivateCustomerSubscriptionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if privatecustomersubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized privatecustomersubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := privatecustomersubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrivateCustomerSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := privatecustomersubscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PrivateCustomerSubscription.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionType(); ok {
		if err := privatecustomersubscription.SubscriptionTypeValidator(v); err != nil {
			return &ValidationError{Name: "subscription_type", err: fmt.Errorf(`ent: validator failed for field "PrivateCustomerSubscription.subscription_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCents(); ok {
		if err := privatecustomersubscription.AmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "PrivateCustomerSubscription.amount_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *PrivateCustomerSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(privatecustomersubscription.Table, privatecustomersubscription.Columns, sqlgraph.NewFieldSpec(privatecustomersubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(privatecustomersubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(privatecustomersubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(privatecustomersubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(privatecustomersubscription.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionType(); ok {
		_spec.SetField(privatecustomersubscription.FieldSubscriptionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(privatecustomersubscription.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(privatecustomersubscription.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresOn(); ok {
		_spec.SetField(privatecustomersubscription.FieldExpiresOn, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReminderSentForExpiry(); ok {
		_spec.SetField(privatecustomersubscription.FieldReminderSentForExpiry, field.TypeTime, value)
	}
	if _u.mutation.ReminderSentForExpiryCleared() {
		_spec.ClearField(privatecustomersubscription.FieldReminderSentForExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.ReminderSentAt(); ok {
		_spec.SetField(privatecustomersubscription.FieldReminderSentAt, field.TypeTime, value)
	}
	if _u.mutation.ReminderSentAtCleared() {
		_spec.ClearField(privatecustomersubscription.FieldReminderSentAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{privatecustomersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PrivateCustomerSubscriptionUpdateOne is the builder for updating a single PrivateCustomerSubscription entity.
type PrivateCustomerSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrivateCustomerSubscriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetDeletedAt(v time.Time) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableDeletedAt(v *time.Time) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) ClearDeletedAt() *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetName(v string) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableName(v *string) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubscriptionType sets the "subscription_type" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetSubscriptionType(v string) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetSubscriptionType(v)
	return _u
}

// SetNillableSubscriptionType sets the "subscription_type" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableSubscriptionType(v *string) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetSubscriptionType(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetAmountCents(v int64) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableAmountCents(v *int64) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) AddAmountCents(v int64) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetExpiresOn sets the "expires_on" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetExpiresOn(v time.Time) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetExpiresOn(v)
	return _u
}

// SetNillableExpiresOn sets the "expires_on" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableExpiresOn(v *time.Time) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetExpiresOn(*v)
	}
	return _u
}

// SetReminderSentForExpiry sets the "reminder_sent_for_expiry" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetReminderSentForExpiry(v time.Time) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetReminderSentForExpiry(v)
	return _u
}

// SetNillableReminderSentForExpiry sets the "reminder_sent_for_expiry" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableReminderSentForExpiry(v *time.Time) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetReminderSentForExpiry(*v)
	}
	return _u
}

// ClearReminderSentForExpiry clears the value of the "reminder_sent_for_expiry" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) ClearReminderSentForExpiry() *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.ClearReminderSentForExpiry()
	return _u
}

// SetReminderSentAt sets the "reminder_sent_at" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetReminderSentAt(v time.Time) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.SetReminderSentAt(v)
	return _u
}

// SetNillableReminderSentAt sets the "reminder_sent_at" field if the given value is not nil.
func (_u *PrivateCustomerSubscriptionUpdateOne) SetNillableReminderSentAt(v *time.Time) *PrivateCustomerSubscriptionUpdateOne {
	if v != nil {
		_u.SetReminderSentAt(*v)
	}
	return _u
}

// ClearReminderSentAt clears the value of the "reminder_sent_at" field.
func (_u *PrivateCustomerSubscriptionUpdateOne) ClearReminderSentAt() *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.ClearReminderSentAt()
	return _u
}

// Mutation returns the PrivateCustomerSubscriptionMutation object of the builder.
func (_u *PrivateCustomerSubscriptionUpdateOne) Mutation() *PrivateCustomerSubscriptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PrivateCustomerSubscriptionUpdate builder.
func (_u *PrivateCustomerSubscriptionUpdateOne) Where(ps ...predicate.PrivateCustomerSubscription) *PrivateCustomerSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PrivateCustomerSubscriptionUpdateOne) Select(field string, fields ...string) *PrivateCustomerSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PrivateCustomerSubscription entity.
func (_u *PrivateCustomerSubscriptionUpdateOne) Save(ctx context.Context) (*PrivateCustomerSubscription, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrivateCustomerSubscriptionUpdateOne) SaveX(ctx context.Context) *PrivateCustomerSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PrivateCustomerSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrivateCustomerSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrivateCustomerSubscriptionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if privatecustomersubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized privatecustomersubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := privatecustomersubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrivateCustomerSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := privatecustomersubscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PrivateCustomerSubscription.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionType(); ok {
		if err := privatecustomersubscription.SubscriptionTypeValidator(v); err != nil {
			return &ValidationError{Name: "subscription_type", err: fmt.Errorf(`ent: validator failed for field "PrivateCustomerSubscription.subscription_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCents(); ok {
		if err := privatecustomersubscription.AmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "PrivateCustomerSubscription.amount_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *PrivateCustomerSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *PrivateCustomerSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(privatecustomersubscription.Table, privatecustomersubscription.Columns, sqlgraph.NewFieldSpec(privatecustomersubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PrivateCustomerSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, privatecustomersubscription.FieldID)
		for _, f := range fields {
			if !privatecustomersubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != privatecustomersubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(privatecustomersubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(privatecustomersubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(privatecustomersubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(privatecustomersubscription.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionType(); ok {
		_spec.SetField(privatecustomersubscription.FieldSubscriptionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(privatecustomersubscription.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(privatecustomersubscription.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresOn(); ok {
		_spec.SetField(privatecustomersubscription.FieldExpiresOn, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReminderSentForExpiry(); ok {
		_spec.SetField(privatecustomersubscription.FieldReminderSentForExpiry, field.TypeTime, value)
	}
	if _u.mutation.ReminderSentForExpiryCleared() {
		_spec.ClearField(privatecustomersubscription.FieldReminderSentForExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.ReminderSentAt(); ok {
		_spec.SetField(privatecustomersubscription.FieldReminderSentAt, field.TypeTime, value)
	}
	if _u.mutation.ReminderSentAtCleared() {
		_spec.ClearField(privatecustomersubscription.FieldReminderSentAt, field.TypeTime)
	}
	_node = &PrivateCustomerSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{privatecustomersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
