// Code generated by ent, DO NOT EDIT.

package businessexchangerate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldMonth, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldCurrency, v))
}

// RateScaled applies equality check predicate on the "rate_scaled" field. It's identical to RateScaledEQ.
func RateScaled(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldRateScaled, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldSource, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldUpdatedAt, v))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v time.Time) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldMonth, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldContainsFold(FieldCurrency, v))
}

// RateScaledEQ applies the EQ predicate on the "rate_scaled" field.
func RateScaledEQ(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldRateScaled, v))
}

// RateScaledNEQ applies the NEQ predicate on the "rate_scaled" field.
func RateScaledNEQ(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldRateScaled, v))
}

// RateScaledIn applies the In predicate on the "rate_scaled" field.
func RateScaledIn(vs ...int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldRateScaled, vs...))
}

// RateScaledNotIn applies the NotIn predicate on the "rate_scaled" field.
func RateScaledNotIn(vs ...int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldRateScaled, vs...))
}

// RateScaledGT applies the GT predicate on the "rate_scaled" field.
func RateScaledGT(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldRateScaled, v))
}

// RateScaledGTE applies the GTE predicate on the "rate_scaled" field.
func RateScaledGTE(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldRateScaled, v))
}

// RateScaledLT applies the LT predicate on the "rate_scaled" field.
func RateScaledLT(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldRateScaled, v))
}

// RateScaledLTE applies the LTE predicate on the "rate_scaled" field.
func RateScaledLTE(v int64) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldRateScaled, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldContainsFold(FieldSource, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.FieldContainsFold(FieldNotes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BusinessExchangeRate) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BusinessExchangeRate) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BusinessExchangeRate) predicate.BusinessExchangeRate {
	return predicate.BusinessExchangeRate(sql.NotPredicates(p))
}
