// Code generated by ent, DO NOT EDIT.

package businesscostitem

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the businesscostitem type in the database.
	Label = "business_cost_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCostClass holds the string denoting the cost_class field in the database.
	FieldCostClass = "cost_class"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldAmountMinor holds the string denoting the amount_minor field in the database.
	FieldAmountMinor = "amount_minor"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldBillingCycle holds the string denoting the billing_cycle field in the database.
	FieldBillingCycle = "billing_cycle"
	// FieldStartsOn holds the string denoting the starts_on field in the database.
	FieldStartsOn = "starts_on"
	// FieldEndsOn holds the string denoting the ends_on field in the database.
	FieldEndsOn = "ends_on"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountIdentifier holds the string denoting the account_identifier field in the database.
	FieldAccountIdentifier = "account_identifier"
	// FieldIsFree holds the string denoting the is_free field in the database.
	FieldIsFree = "is_free"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// Table holds the table name of the businesscostitem in the database.
	Table = "business_cost_items"
)

// Columns holds all SQL columns for businesscostitem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldCostClass,
	FieldCategory,
	FieldAmountMinor,
	FieldCurrency,
	FieldBillingCycle,
	FieldStartsOn,
	FieldEndsOn,
	FieldAccountID,
	FieldAccountIdentifier,
	FieldIsFree,
	FieldActive,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CostClassValidator is a validator for the "cost_class" field. It is called by the builders before save.
	CostClassValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// AmountMinorValidator is a validator for the "amount_minor" field. It is called by the builders before save.
	AmountMinorValidator func(int64) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// BillingCycleValidator is a validator for the "billing_cycle" field. It is called by the builders before save.
	BillingCycleValidator func(string) error
	// AccountIdentifierValidator is a validator for the "account_identifier" field. It is called by the builders before save.
	AccountIdentifierValidator func(string) error
	// DefaultIsFree holds the default value on creation for the "is_free" field.
	DefaultIsFree bool
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// OrderOption defines the ordering options for the BusinessCostItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCostClass orders the results by the cost_class field.
func ByCostClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostClass, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByAmountMinor orders the results by the amount_minor field.
func ByAmountMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountMinor, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByBillingCycle orders the results by the billing_cycle field.
func ByBillingCycle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingCycle, opts...).ToFunc()
}

// ByStartsOn orders the results by the starts_on field.
func ByStartsOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsOn, opts...).ToFunc()
}

// ByEndsOn orders the results by the ends_on field.
func ByEndsOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsOn, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountIdentifier orders the results by the account_identifier field.
func ByAccountIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountIdentifier, opts...).ToFunc()
}

// ByIsFree orders the results by the is_free field.
func ByIsFree(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFree, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}
